### ISSUE TITLE
Two factor login on webauth not working

### ISSUE THREAD

**Issue by itsjfx** [ValvePython/steam#104]
Hi, I'm facing an issue where I cannot login to the webauth without first logging through the client. The "get_web_session()" method works perfectly, but the example from (https://steam.readthedocs.io/en/latest/api/steam.webauth.html) does not.

This is what the output looks like: https://gist.githubusercontent.com/itsjfx/d6ce1ca445173dcfc4d54f4898f4d9c9/raw/4a79a5f7f257a4ef6727b47fb05f03832b61e603/output.py

I can confirm the correct totp code is being sent.

**Comment by itsjfx** [comment]
Thought I should include my code, here it is - just the example modified to generate the totp and enter the correct credentials, which are obviously redacted.

https://gist.githubusercontent.com/itsjfx/4da2891ab5b3df64699b18fc15761763/raw/6ef7006413cb2d5e5bc0fe2c5101ca747eacc082/in.py

**Comment by itsjfx** [comment]
Looks like the issue was in sa.generate_twofactor_code - when I used this for a certain account it would incorrectly generate the wrong two_factor_code, but when I used a different library (https://github.com/philippj/steam-totp) it worked perfectly. I guess I'll switch to this one instead.

**Comment by rossengeorgiev** [comment]
Hi, there is no issue with `generate_twofactor_code()`. You have to provide the shared secret bytes. If you are providing them base64 encoded it won't generate the correct code.

If you have the JSON from your phone, you can use it with `SteamAuthenticator` .

It is also worth noting that the codes are one time use only and are in intervals of 30 seconds.

**Comment by itsjfx** [comment]
It's using the identity_secret taken from the .maFiles generated by SDA.
How would you recommend converting it to a format `generate_twofactor_code()` will recognize? It will be great to know so I don't need to include another library.

Thanks,
jfx

**Comment by rossengeorgiev** [comment]
I'm unfamiliar with SDA or its' file format. You need to provide the `shared secret` in raw bytes (not encoded). `identity_secret` is used for trading confirmation.

The phone steam authenticator stores those secrets in JSON format, and they are base64 encoded. If you have that, you can pass it to `SteamAuthenticator(secrets=dict_secrets)`.

**Comment by itsjfx** [comment]
My mistake, I meant to write 'shared_secret. I guess I'll just do a base64 decode of that, thanks for your help.

**Comment by rossengeorgiev** [comment]
Closing this as it looks resolved
