### ISSUE TITLE
Any knowledge of the exact steamclient rate limit?

### ISSUE THREAD

**Issue by DashLt** [ValvePython/steam#111]
I'm trying to make a large number of accounts for steam key farming purposes, and I keep getting rate limited, even with delays of 10 seconds. They all have different names, different passwords, and different emails. Does anybody know a good timeout for usage of the steam client?

**Comment by rossengeorgiev** [comment]
Steam doesn't provide information about rate limits, so you will have to find out on your own. I imagine account creation is heavily rate limited for obvious reasons.

**Comment by DashLt** [comment]
Very old, but I found that an interval of 60 seconds worked, which is unfortunately quite slow.
