### ISSUE TITLE
api.ISteamUserStats.GetPlayerAchievements sends bad request

### ISSUE THREAD

**Issue by deKaf** [ValvePython/steam#113]
Heya,

I was writing a python script and ran into using GetPlayerAchievements:

`achievements = api.ISteamUserStats.GetPlayerAchievements( appid = appID, steamid = userID)`

which returns this error:
`requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.steampowered.com/ISteamUserStats/GetPlayerAchievements/v1/?steamid=76561197972495328&key=XXXXXXXXXXXX&format=json&appid=359550`

This looks incorrect according to Valve's web API documentation which expects this format:
: 
`http://api.steampowered.com/ISteamUserStats/GetPlayerAchievements/v0001/?appid=440&key=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&steamid=76561197972495328`

Or perhaps I'm

**Comment by deKaf** [comment]
Nevermind, this was my fault - I'm stupid :(

**Comment by rossengeorgiev** [comment]
:(
