### ISSUE TITLE
Can I redeem the steam keys?

### ISSUE THREAD

**Issue by Rzeszow** [ValvePython/steam#118]
Hi,
Can I redeem the steam game keys?
`XXXXX-XXXXX-XXXXX`
`([A-Za-z0-9]){5}-([A-Za-z0-9]){5}-([A-Za-z0-9]){5}`

**Comment by rossengeorgiev** [comment]
http://steam.readthedocs.io/en/latest/api/steam.client.builtins.html#steam.client.builtins.apps.Apps.register_product_key

**Comment by Rzeszow** [comment]
Thanks.
