### ISSUE TITLE
Last character cut out in chat message

### ISSUE THREAD

**Issue by LaBlazer** [ValvePython/steam#120]
Few days ago my bot stopped working so i checked the console and every message that it received had the last character cut so it was not recognizing the commands... I did not touch the code so something had to change on steams side...
![bug](https://user-images.githubusercontent.com/6269859/29925295-2c664e38-8e60-11e7-946b-5eb9a60a7995.png)

**Comment by rossengeorgiev** [comment]
Hi! Thanks for the report. Looks like Valve no longer send the text as null terminated string.
