### ISSUE TITLE
Echoing Words does not work

### ISSUE THREAD

**Issue by droblue** [ValvePython/steam#122]
@client.on(client.EVENT_CHAT_MESSAGE)
def handle_chat_message(user, text):
    user.send_message("You said: " + text)

This code does not seem to work when implemented i have even put a print statement within in it to test to to see if it ran. I had a friend message me but he was never replied to but I got the message "Ran" while he got no response so I was wondering what went wrong and if i am doing this right or not. Is it because I am using pycharm edu by chance or something else?

@client.on(client.EVENT_CHAT_MESSAGE)
def handle_chat_message(user, text):
    print("Ran"
    user.send_message("You said: " + text)

**Comment by rossengeorgiev** [comment]
Hi, I can't answer you as you don't provide me enough context to determine why it doesn't work. Here is an example with the minimal code to get echo messages:

```python
from steam import SteamClient

client = SteamClient()

@client.on(client.EVENT_CHAT_MESSAGE)
def echo(user, text):
    user.send_message("You said: " + text)

client.cli_login()
client.run_forever()

**Comment by droblue** [comment]
Thank you I'll try it but could this be used the same way to set up commands for the bot so if the bot gets a certain message such as !help it will display all of the different responses or would there be a more efficient way of doing this.

**Comment by droblue** [comment]
for some reason client.logout() was not letting it function correctly even if i put it in separate parts of the code.
