### ISSUE TITLE
Automated login but cant access user

### ISSUE THREAD

**Issue by droblue** [ValvePython/steam#124]
```
class BotSystem():
    def __init__(self, authentication, client, username, password):
        self.client = client
        self.authentication = authentication
        self.username = username
        self.password = password
        self.client.login(self.username, self.password, self.authentication.get_code())
    def Botstatus(self):
```

        print("Logged on as: %s" % self.client.user.name)
        print("Community profile: %s" % self.client.steam_id.community_url)
        print("Last logon: %s" % self.client.user.last_logon)
        print("Last logoff: %s" % self.client.user.last_logoff)
        print("Number of friends: %d" % len(self.client.friends))

So i was trying to run this code but it kept throwing the error     
 ```
print("Logged` on as: %s" % self.client.user.name)
AttributeError: 'NoneType' object has no attribute 'name'
```
So i used what you recommended for automating the code using the secrets but does that not bring in the user because in the other code with the client.cli_login("username", "password) where you put in the steam code seems to return a user value which can be used to print what im trying to print. But does the automated version not return a user? if so how could i get the user value?

**Comment by rossengeorgiev** [comment]
The `user` property is only `None` when the `SteamClient` instance is not logged in. Either you are calling `BotStatus` before the login has completed, or the login has failed. The `friends` property also has its own event for when it has completed initialization.

**Comment by droblue** [comment]
How would one automatically login giving the secrets? I just want to make sure im doing this right

**Comment by droblue** [comment]
nvm figured it out gotta love coding and all the little things...

**Comment by rossengeorgiev** [comment]
There are some examples at https://github.com/ValvePython/steam/tree/master/recipes/1.Login

Call `login()` on connect, use `reconnect()` on disconnect, have a variable to decide whether to reconnect in case you want to shutdown your app and exit.
