### ISSUE TITLE
Missing PICS update

### ISSUE THREAD

**Issue by Vastrix** [ValvePython/steam#125]
Hey,

Software | Version
-- | --
Python | 3.6.1
Steam | v0.8.18 (The changes didn't imply anything significant)

Can someone confirm that change [3379291](https://steamdb.info/changelist/3379291/) is **only** found in the `app_changes` list even tho it also has a package update?

Cause if that's the case, I've missed a few important package updates.. :s

If so, I'd like to report this issue :)

**Comment by rossengeorgiev** [comment]
If its on SteamDB, it happened. I assume you are using `get_changes_since(change_number, app_changes=True, package_changes=False)`. You might have missed that by default it doesn't request package changes. So you have to call it like this `get_changes_since(12345, True, True)` if you want everything.

**Comment by Vastrix** [comment]
Nope, I wish it was that simple :P 

```Python
self.client.get_changes_since(changeNum, package_changes=True)
```

**Comment by rossengeorgiev** [comment]
Then you are no checking often enough. Technically, you can't catch every change if they happen fast enough.

**Comment by Vastrix** [comment]
So if I now try to fetch the changes since `3379290` (which by now is a while ago)
I can get a response that doesn't include certain changes??

**Comment by rossengeorgiev** [comment]
Not odd, its how it works. You get the latest change number. If there were change numbers between the latest and `3379290` you wont get them. You wont be able to see the changes. SteamDB checks every second, and it manages to catch most change numbers. It's just how Steam works.

**Comment by Vastrix** [comment]
But if I now do:
```Python
self.client.get_changes_since(3379290, package_changes=True)
```
I get like a few thousand changes..
Ranging from that change number till now...

sooo, it does look like you can give up whichever change number you want (up until a certain point) and get the backlog..?

**Comment by rossengeorgiev** [comment]
You get all the apps and packages (and their last change number) that have changed since the change number you provided. Remember that this is only used so the client can tell which apps need updating. It's not supposed to give you a history of all changes. This is the sole reason SteamDB exists, to track history

**Comment by Vastrix** [comment]
ooh :o 
I see,

So how do you get all packages then?
Just shorten the interval between `get_changes_since`, or using web sockets? (if web sockets, can you give a hint/link as to how to implement it? (there is very little documentation regarding steamkit in general out there))

**Comment by Vastrix** [comment]
Right, I talked to Xpaw.. :/
And turns out the response should contain all package updates since the given change number..
![chat](https://puu.sh/xwYuF/44e38982c6.png)

**Comment by rossengeorgiev** [comment]
Correct, you contains all the packages that have been updated. It doesn't contain all the updates that had happened.

**Comment by Vastrix** [comment]
aaaaaah

So, if a package gets updated twice, it will only show you the last update? :o

**Comment by rossengeorgiev** [comment]
Yes.

**Comment by Vastrix** [comment]
\o/

Awesome, Thanks for putting up with this question for so long :)
