### ISSUE TITLE
How to change logging level?

### ISSUE THREAD

**Issue by berdt** [ValvePython/steam#128]
Hi,

I want to change the logging level to INFO, how would I do that? 
Can I pass it somehow when I create SteamClient for example? Say I have this code:

```
from steam import SteamClient

client = SteamClient()
client.anonymous_login()
```

**Comment by rossengeorgiev** [comment]
Something like this?

```python
import logging
logging.basicConfig(level=logging.INFO)

**Comment by berdt** [comment]
Sorry maybe I was not clear enough. The logging statements within the library, e.g. 

`self._LOG.debug("Attempting Anonymous login")`

These statements are not being printed so I figured I have to somehow change the logging level for them to show. Is it clear now what I mean?

**Comment by rossengeorgiev** [comment]
Have you tried setting it to debug?
```python
logging.basicConfig(level=logging.DEBUG)
```

**Comment by berdt** [comment]
Thanks for the help, great library.
