### ISSUE TITLE
games_played fails to work.

### ISSUE THREAD

**Issue by Zwork101** [ValvePython/steam#130]
I've been looking at getting the account `http://steamcommunity.com/id/thetf2tradebot/`, to play the game tf2, with a steamid of 440 with the following code:
```py
client.login('zworktradebot', 'pass', two_factor_code=guard.generate_one_time_code('xxx'))
print('Logged in!')

client.games_played([440])
```
The code ends up doing nothing, I was looking at: `https://github.com/DoctorMcKay/node-steam-user/blob/e6c6b5a15cc7b8ed831562b9bcae114a4ced3755/components/apps.js`, and from what I can see, works, and doesn't supply a 'games_played', and just sends the list, but I could be wrong. Any ideas why this is happening?

**Comment by rossengeorgiev** [comment]
Nope, it works just fine. The problem is that you are not engaging with the subsequent communication with TF2 game coordinator.

**Comment by Phalelashvili** [comment]
how do you "engage subsequent communication with game coordinator"?

**Comment by rossengeorgiev** [comment]
By extending the GameCoordinator class, which can handle the communication and having the specific protobufs to (de)serialize the messages. You can use the following to as a reference:

https://github.com/ValvePython/dota2 implements its for Dota 2
https://github.com/ValvePython/csgo for CS: Global Offensive

**Comment by Phalelashvili** [comment]
custom GameCoordinator is required for every single game?

**Comment by rossengeorgiev** [comment]
Yes, all 3 games have different GCs.
