### ISSUE TITLE
Get Friend List

### ISSUE THREAD

**Issue by helsyQ** [ValvePython/steam#131]
Hello. How can i get a friend list to work with: add or remove it depending on relationship status. Because if i do `print(list(client.friends))` i get not right form of list, it does not have relation ship status. The main thing i need to manage friends depends on relationship status. Help me please.

**Comment by Zwork101** [comment]
What do you mean by relationship status?

**Comment by helsyQ** [comment]
I mean RequestInitiator or RequestRecipient.
`from steam.enums import EResult, EFriendRelationship`
I need to list all friends who i added, but they did not accept my invite yet.

**Comment by rossengeorgiev** [comment]
`list(client.friends)` will give you a list of `SteamUser` instances. Those have a `relationship` property: http://steam.readthedocs.io/en/latest/api/steam.client.user.html#steam.client.user.SteamUser.relationship

What you could do is filter on that property like this:

```python

def invites_only(friend):
   return friends.relationship == EFriendRelationship.RequestRecipient

pending_friends = list(filter(invites_only, client.friends))

**Comment by helsyQ** [comment]
Thanks a lot! My mistake was i didn't see that relationship status does not print if i do print(list(client.friends)). The same way i can filter EPersonaState, right ? Because if i print pending_friends i see that all users are offline, since they are online.

**Comment by rossengeorgiev** [comment]
Steam won't tell you the status of users you are not friends with.

**Comment by helsyQ** [comment]
Could you help me how can i get filter friends the same way by Online ? 
If i use 
```
def online_only(SteamUser):
   return SteamUser.state == EPersonaState.Online

online_friends = list(filter(online_only, client.friends))
print(online_friends)

```
I got `[]` .

**Comment by rossengeorgiev** [comment]
That should work. You could be that you are offline, that you are running that code at the wrong time, I don't know. I don't provide general programming help. Good luck
