### ISSUE TITLE
No gameextrainfo in output

### ISSUE THREAD

**Issue by SRPlatin** [ValvePython/steam#133]
After running:
```
steam_api_response = steam_web_api_key.ISteamUser.GetPlayerSummaries(steamids=ids)["response"]

print(steam_api_response)
```

The Output is:

`{'players': [{'timecreated': 1303734791, 'personastate': 1, 'loccityid': -, 'personaname': 'SR_Lut3t1um', 'steamid': '76561198041094627', 'profileurl': 'http://steamcommunity.com/id/SR_Lut3t1um/', 'profilestate': 1, 'commentpermission': 1, 'avatarmedium': 'https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/c8/c80b4044eef9178e7fe073b22cc62fc6b1000ea5_medium.jpg', 'lastlogoff': 1514471789, 'communityvisibilitystate': 3, 'avatar': 'https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/c8/c80b4044eef9178e7fe073b22cc62fc6b1000ea5.jpg', 'loccountrycode': 'DE', 'locstatecode': -, 'personastateflags': 0, 'gameid': '326460', 'realname': -, 'primaryclanid': '-', 'avatarfull': -}]}`

So missing the gameextrainfo with I should get, stated in this docu; https://developer.valvesoftware.com/wiki/Steam_Web_API#GetPlayerSummaries_.28v0002.29

**Comment by rossengeorgiev** [comment]
Hi @SRPlatin, that documentation is very outdated. Valve has changed a lot of the APIs, mainly removing things, so I assume that is a bit they removed.
