### ISSUE TITLE
Add example for displaying on-game status

### ISSUE THREAD

**Issue by Zwork101** [ValvePython/steam#135]
I have tried, to no avail, create a program that was able to display an in game status, as unlike node-steam-user, you have to connect to the game server. This is fine, but I'm lead to believe an example is needed.

**Comment by rossengeorgiev** [comment]
Are you referring to in-game status, as when someone is playing a game, what game is it and son ?

**Comment by Zwork101** [comment]
That's the one

**Comment by rossengeorgiev** [comment]
That status is available on steamcommunity for public profiles. You can also get it if you are friends with the player from Steam. There also rich presence in games that support it. I don't know what you are trying to do

**Comment by Zwork101** [comment]
I'm suggesting we add an example, for what to do, to make steam display you as "Playing TF2" or "Playing CSGO"

**Comment by rossengeorgiev** [comment]
There is no example since there is no API for that at moment. `games_played()` could be improved to work the same was as `node-steam-user`.

**Comment by Zwork101** [comment]
Ah, well either changing the way games_played to be like node-steam-user, or adding documentation on how to acheive the same result as node-steam-user.

**Comment by deluxghost** [comment]
How to get the details of in-game status? Games like Dota2/CSGO/TF2, they can tell a player is in Main Menu or in some game mode, and the map name, etc, which we can see these data in the new steam friend UI. I think they can be fetched in steamcm, but dunno where they are.

**Comment by rossengeorgiev** [comment]
The term in steam for that is `rich presence` and it depends on the game.

**Comment by rossengeorgiev** [comment]
Closed in fa8a512
