### ISSUE TITLE
[Question] Can this be used to get build history for a game?

### ISSUE THREAD

**Issue by joshhills** [ValvePython/steam#141]
Apologies for making an issue, I'm in dire need of the kind of information present on pages like https://steamdb.info/app/440/history/ but I haven't the foggiest how to get that; the Steam Web API requires a publisher key for the same information, but it must be available somehow.

Thankyou

**Comment by joshhills** [comment]
Cheers, do you know if the Steam DB backend you've linked comes with the historical data, or is it the case that I would have to start my own monitoring henceforth? I'm trying to get my hands on essentially list of updates per game since release.

**Comment by rossengeorgiev** [comment]
It doesn't come with data. What you are trying to do is impossible for any game already released. Best you can do is scrap steamdb.
