### ISSUE TITLE
Arch User Repository packages

### ISSUE THREAD

**Issue by vanyasem** [ValvePython/steam#145]
I packaged `python-steam` for Arch GNU/Linux in AUR:

Packages: [python2-steam-git](https://aur.archlinux.org/packages/python2-steam-git/), [python-steam-git](https://aur.archlinux.org/packages/python-steam-git/), [python2-steam](https://aur.archlinux.org/packages/python2-steam/), [python-steam](https://aur.archlinux.org/packages/python-steam/)

Packages suffixed with `-git` are built from git source, others are built from the lastest release tarball

Packages prefixed with `python-` are built for Python 3.x, and prefixed with `python2-` are built for Python 2.x

You can install them using any AUR helper (the recommended one is `pacaur`):
```
pacaur -S python-steam
```

You can also install them manually:
```
git clone https://aur.archlinux.org/python-steam.git
cd python-steam
makepkg -sic
```

It would be great if you added them to your readme

**Comment by rossengeorgiev** [comment]
Hi, this is interesting.
What is the advantage of having AUR packages over using pypi? (I don't use arch).
How are these packages built?

**Comment by vanyasem** [comment]
The advantage is that it's a native package for Arch and it's integrated into the Arch package manager _(pacman)_. This concept is present in every other distribution.

They are built by user via a PKGBUILD (that's how AUR works). You can see the script [here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-steam).

**Comment by rossengeorgiev** [comment]
I don't see any issues in providing AUR packages. The only thing I would like to see is a repo with the build scripts inside this org, so that the build are reproducible. I can setup a repo if you want to do that

**Comment by vanyasem** [comment]
@rossengeorgiev I have already set up AUR packages and asked to mention them in the README. Look at the issue, it has links to ready-to-use packages. They already have their repos on AUR, and are updated (maintained) by me

**Comment by vanyasem** [comment]
I am sorry, but why exactly was this issue closed?
