### ISSUE TITLE
Beginner Question: Can I do a "app_info_print" using this package?

### ISSUE THREAD

**Issue by baylf2000** [ValvePython/steam#147]
Trying to find a way to do a programmatic equivalent of "+app_info_print" from steamcmd, but I'm finding the documentation incredibly complicated and difficult to follow.

All I'm after is the buildid for a particular branch of an appid. I can't seem to find a way to get this from the web api.

Any help would be much appreciated.

**Comment by rossengeorgiev** [comment]
Hi @baylf2000, did you manage to get the build ids you were looking for?

**Comment by baylf2000** [comment]
Hi @rossengeorgiev ,

Thanks so much for the follow up. I'm wondering if there's any chance you might have a usage example for the above?

**Comment by rossengeorgiev** [comment]
Something very basic would be

```python
from steam import SteamClient
client = SteamClient()
client.cli_login()
print client.get_product_info(apps=[570])
```
The output is just a huge `dict` with loads of stuff including buildids

**Comment by baylf2000** [comment]
Thank you so much @rossengeorgiev.

I was also able to use `client.anonymous_login()` to avoid needing any login details, just in case this helps anyone else.

Thanks again.
