### ISSUE TITLE
Gevent error in every start

### ISSUE THREAD

**Issue by akagna** [ValvePython/steam#148]
The module gives an error when i use client;
```
MonkeyPatchWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. Please monkey-patch earlier. See https://github.com/gevent/gevent/issues/1016
  _warnings)
```
I don't know if it's can cause any problem but it is annoying to see this error in every run. It seems easy to solve. I just wanted to report. :D

**Comment by rossengeorgiev** [comment]
Hi @akagna, thank for the suggestion, but is not something I or gevent can fix it seems. It already been detailed in #97 

In short, if you are using the `SteamClient` make sure you monkey patch before you do anything else.

**Comment by akagna** [comment]
Thanks @rossengeorgiev, I will be sure about it. Sorry for didn't check if there's any topic about it.
