### ISSUE TITLE
[Question] Can you convert maFiles to the format required by this lib?

### ISSUE THREAD

**Issue by melvyn2** [ValvePython/steam#152]

**Comment by rossengeorgiev** [comment]
Not sure, the file format is exactly what the API returns. Have you tried opening the maFIle directly? Looks like it plain json, unless its encrypted.

**Comment by melvyn2** [comment]
Parsing it as JSON and passing the returned dict as a secret to the `steam.guard.SteamAuthenticator`
class works, and gives valid 2FA codes.
