### ISSUE TITLE
Question: How to send and receive non-Proto message?

### ISSUE THREAD

**Issue by SeRi0uS007** [ValvePython/steam#156]
Hello. How to send and receive non-Proto message which contains binary data, like `ClientOGSBeginSession (5490)`

**Comment by rossengeorgiev** [comment]
Yer `Msg` class instead of `MsgProto`. The implement the struct classes that (de)serialize the messages. See https://github.com/ValvePython/steam/blob/master/steam/core/msg/structs.py#L195 Make sure the class name matches the enum name.

**Comment by SeRi0uS007** [comment]
Thank you. I looked at the source code that you sent and I think I got it.
