### ISSUE TITLE
[Question]Can the api confirm trades, rather than just making codes?

### ISSUE THREAD

**Issue by Piero-Bird** [ValvePython/steam#161]
I know you can generate Steam confirmation codes to confirm trades like so:

`SteamAuthOBJ.get_confirmation_key("details", timeStamp)`

However, how can I see the items in a trade and use this code to confirm them? I was unable to find information on this in the documentation.

Thanks.

**Comment by rossengeorgiev** [comment]
You will have to figure out how its done, or see how one of the existing trading library does it. There are no API for trading in this package.

**Comment by Piero-Bird** [comment]
Thank you. I'm looking at one right now :)

**Comment by justRoomboy** [comment]
> Thank you. I'm looking at one right now :)
You solved this problem?
