### ISSUE TITLE
games_played for any game

### ISSUE THREAD

**Issue by Phalelashvili** [ValvePython/steam#174]
unlike node-steam-user, this library needs game coordinator, but building game coordinator for every game on steam is impossible, i don't need to communicate with game either, just to make steam think i'm playing it/them, is there any way to do it?

**Comment by rossengeorgiev** [comment]
GameCoordiniator is only need for games that have one, and if you want to communicate with it.

Have you tried searching the documentation? https://steam.readthedocs.io/en/latest/search.html?q=games_played

**Comment by Phalelashvili** [comment]
```
from steam.client import SteamClient    
client = SteamClient()
resp = client.login(username, password, two_factor_code=twoFA)
client.games_played([578080])
```
this code doesn't work, after sending games played to socket code exits and steam doesn't change ingame status
**Attempting connection to %s ('155.133.242.9', 27019)
Connected.
EResult.OK**

**Comment by rossengeorgiev** [comment]
Try adding `client.run_forever()` at the end
