### ISSUE TITLE
util function to parse appinfo.vdf and packageinfo.vdf files from Steam's directory

### ISSUE THREAD

**Issue by rossengeorgiev** [ValvePython/steam#179]
Format details at https://github.com/ValvePython/vdf/issues/13#issuecomment-321700244

Requires: https://github.com/ValvePython/vdf/issues/27

**Comment by Jenna3715** [comment]
This might help: https://gist.github.com/lolzballs/d8ad24ed17a381d9de71

**Comment by Jenna3715** [comment]
Also, there appears to be a correlation between the appinfo.vdf and packageinfo.vdf files and the information on https://steamdb.info/ .
