### ISSUE TITLE
Dump steam session

### ISSUE THREAD

**Issue by Phalelashvili** [ValvePython/steam#182]
hey, is there any way to dump session to a file so you won't have to relogin later? pickle doesn't work (because of thread.RLock)

**Comment by Nothing4You** [comment]
What's the point when you can just use the login_key for the new session?

**Comment by Phalelashvili** [comment]
> What's the point when you can just use the login_key for the new session?

login key only works if you're online all the time

**Comment by rossengeorgiev** [comment]
Hi @Phalelashvili, you cannot dump the session, it is only valid as long as you are online. `login_key` is used for the save password feature. So, you need to store either `username+login_key+sentryfile` (email steam guard) or `username+login_key+machine_id` (authenticator steam guard).

**Comment by Phalelashvili** [comment]
> Hi @Phalelashvili, you cannot dump the session, it is only valid as long as you are online. `login_key` is used for the save password feature. So, you need to store either `username+login_key+sentryfile` (email steam guard) or `username+login_key+machine_id` (authenticator steam guard).

i'm using mobile auth, sentry won't work, steam client does it, couldn't find info on what exactly it saves, isn't it possible to revive session using cookies? it works on web client, is it different here?

**Comment by rossengeorgiev** [comment]
Are you using `MobileWebAuth` ?

**Comment by Phalelashvili** [comment]
> Are you using `MobileWebAuth` ?

no, i'm logging in with 2fa code

**Comment by rossengeorgiev** [comment]
It is still unclear what you are using and trying to do. Can you provide example code?

**Comment by Phalelashvili** [comment]
> It is still unclear what you are using and trying to do. Can you provide example code?

there is none? i just asked if it was possible to revive session in your library using cookies

**Comment by rossengeorgiev** [comment]
I see. There isn't any specific method to do that. All web sessions are `requests.Session` instance with corresponding cookies. The various classes and methods will simply fill in the cookies and provide an instance ready to use.  If you have the cookies you can simply set them up on the session instance and make requests. In that case, you only really need the `request` library.

**Comment by Phalelashvili** [comment]
> I see. There isn't any specific method to do that. All web sessions are `requests.Session` instance with corresponding cookies. The various classes and methods will simply fill in the cookies and provide an instance ready to use. If you have the cookies you can simply set them up on the session instance and make requests. In that case, you only really need the `request` library.

I want to use with ur lib, so if i just inject cookies instead of logging in and execute _handle_logon, it's going to work without problem? (can't try atm)
