### ISSUE TITLE
How download 'payload'?

### ISSUE THREAD

**Issue by justRoomboy** [ValvePython/steam#186]
How download 'payload'?
![image](https://user-images.githubusercontent.com/48877848/55730448-07faf100-5a3a-11e9-91fd-e4a6489ce24e.png)

If you get a response through 'wait_msg', the payload is unavailable
![image](https://user-images.githubusercontent.com/48877848/55730401-e7329b80-5a39-11e9-87aa-3fa61de0ecd2.png)

**Comment by rossengeorgiev** [comment]
There is no property payload. The code will attempt to find a message to parse it with based on the EMsg number. That is done automatically, but not every message works. You can manually map a EMsg to message here: https://github.com/ValvePython/steam/blob/master/steam/core/msg/__init__.py#L13-L24

If truly want to get the raw message, you can override `_parse_message` https://github.com/ValvePython/steam/blob/master/steam/core/cm.py#L229

**Comment by justRoomboy** [comment]
That need for this _parse_message, i send response (wait_msg)
