### ISSUE TITLE
create_emergency_codes does not generate any codes

### ISSUE THREAD

**Issue by melvyn2** [ValvePython/steam#187]
The function `create_emergency_codes()` simply returns `[]`. I do receive a confirmation code to create backup codes from my phone, but can do nothing with it.

**Comment by rossengeorgiev** [comment]
That was fixed in 1f86e9ff6715e59343f19dd30ec80a846442edc0. But it was not released. You can install the package from the repo directly or apply the change yourself.

**Comment by melvyn2** [comment]
I was using `MobileWebAuth`.

**Comment by rossengeorgiev** [comment]
Right. They've added a code that needs to be provided to create emergency codes.
