### ISSUE TITLE
OverflowError: Python int too large to convert to C long

### ISSUE THREAD

**Issue by rossengeorgiev** [ValvePython/steam#19]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/steam/client/__init__.py", line 341, in anonymous_login
    message.header.steamid = SteamID(type='AnonUser', universe='Public')
  File "/usr/lib/python2.7/site-packages/steam/steamid.py", line 43, in __new__
    return super(SteamID, cls).__new__(cls, steam64)
OverflowError: Python int too large to convert to C long
```

Happens under python2.7 32bit and not in 64bit.

Best to conditionally subclass at runtime from `long` for py2 and `int` for py3.  
Need to verify that `long` won't cause problems when assigning to protobuf properties.

**Comment by SleepProgger** [comment]
I don't have a testcase, but using an long for the user steamid is what i did in pysteamkit without any problems. All steamids are defined in protobuf as `TYPE_FIXED64` anyway.  
Also from the protobuf docs:
` 64-bit or unsigned 32-bit integers are always represented as long when decoded, but can be an int if an int is given when setting the field. `
