### ISSUE TITLE
Chat module

### ISSUE THREAD

**Issue by MeridianPY** [ValvePython/steam#193]
Just a quick question: Does the new chat module work with the new webhook system? Or is it broken? Since thats the main Feature I would need. Thanks in advance!

**Comment by rossengeorgiev** [comment]
There is no new chat module at the moment. What webhook system are you referring to?

**Comment by MeridianPY** [comment]
The steampy project had issues because Steam updated its chat system when it came out of beta. I think bukson stated, that its now based on webhooks or something like that and he isn't able to reverse-engineer that protocol, so he dropped his chat module. I was just wondering, if you had the same issue here.

**Comment by rossengeorgiev** [comment]
Oh I see, you mean websockets. Yes, the chat page now talks to Steam directly, which is slightly more complicated than a few HTTP calls. While this package might implement the steam protocol over websockets, that is not needed for the moment. You just use `SteamClient` to talk directly to Steam.

I had a look at `steampy`. Good to see that the author has copied code from the `guard` module without honoring the MIT license. The chat module appears to only do direct messages, which you can do with:

Receive: https://steam.readthedocs.io/en/latest/api/steam.client.builtins.html#steam.client.builtins.user.User.EVENT_CHAT_MESSAGE
Send: https://steam.readthedocs.io/en/latest/api/steam.client.user.html#steam.client.user.SteamUser.send_message

**Comment by MeridianPY** [comment]
Oh ok :) Thank you!

**Comment by MeridianPY** [comment]
So I looked at the docs but could quite get the concept: Are those direct functions I can call or do I first have to create a class?

**Comment by rossengeorgiev** [comment]
There are some code examples at https://github.com/ValvePython/steam/tree/master/recipes

A simple code to parrot messages back can look like this:

```python
from steam.client import SteamClient

client = SteamClient()

@client.on(client.EVENT_DISCONNECTED)
def handle_disconnect():
    if client.relogin_available:
        client.relogin()

@client.on(client.EVENT_CHAT_MESSAGE)
def handle_direct_message(user, text):
    user.send_message(text)

client.cli_login()

try:
    client.run_forever()
except KeyboardInterrupt:
    client.disconnect()
```

**Comment by MeridianPY** [comment]
Okay thanks for explaining this in detail :)
