### ISSUE TITLE
Login with given credentials

### ISSUE THREAD

**Issue by MeridianPY** [ValvePython/steam#194]
I feel like this question is really dumb and I'm just too stupid to use this library correctly, but how would I login to steam with all given credentials (Username, Password, secrets) automatically (without user input) and send chat messages to a user by steam id? I'm really sorry if this is so obvious but I just can't work it out.

**Comment by rossengeorgiev** [comment]
You have to provide all the credentials to login. If 2FA is setup, you need to use the 2FA secret to generate a code and provide it on login. If you have email, then you need to figure out of way of getting that token and inputting into the login. 

Then you can `client.get_user(<steam64>).send_message(text)`. Don't use this to try and spam users, you will get banned.

**Comment by MeridianPY** [comment]
Thats what I'm trying to figure out. I have those secrets but how would I apply those to login without any user input?
