### ISSUE TITLE
login key

### ISSUE THREAD

**Issue by invis166** [ValvePython/steam#200]
login key is this thing https://steamcommunity.com/dev/apikey right? 
if so why when im loggining with this key i always getting invalid password error ? im putting it in login_key value ofc

**Comment by rossengeorgiev** [comment]
No that apikey. See https://steam.readthedocs.io/en/v0.9.1/api/steam.client.html#steam.client.SteamClient.relogin

**Comment by invis166** [comment]
So your lib doesnt support using api key?

**Comment by invis166** [comment]
I found key field in WebAuth, is this api key?

**Comment by invis166** [comment]
i solve my problem
