### ISSUE TITLE
Receiving help with code

### ISSUE THREAD

**Issue by Gobot1234** [ValvePython/steam#204]
Hi, I'm looking to learn how to use this module and get started. I was wondering what the best way to get in contact with someone who knows what they are doing? If there is no current way to get in contact with someone could I perhaps suggest a Discord server?

Thanks :)

**Comment by rossengeorgiev** [comment]
There is an IRC channel. There might be a discord in the future.

**Comment by Gobot1234** [comment]
I can't connect to it I might just be being stupid I'm trying this website:
http://www.123freechatnow.com/chatrooms/chatstart.html?server=irc.gamesurge.net&chatroom=opensteamworks
I've tried this as well but it seems to be for a different thing:
https://gamesurge.net/chat/

Thanks again
