### ISSUE TITLE
Login in issue

### ISSUE THREAD

**Issue by stargame25** [ValvePython/steam#205]
In recent developments i found bug with login in stage
If you trying to login in (making bad requests on purpose) several times you will get a captcha, after you got captcha you trying to login in properly, and if you have Steam Guard or 2FA you will not be able to log in because even though you wrote the captcha, you get another one but it's not showing and throwing exception. 
Same issue have the Steam site, which if you try loggin in like previous with captcha, after you submiting Steam Guard or 2FA, login form will give you error and additional captcha, after writting it, it will pass you
https://i.imgur.com/9kUhmEb.png

**Comment by rossengeorgiev** [comment]
This might be fixed in `v1.0.0`. What version are you using?

**Comment by stargame25** [comment]
I was using version 0.9.0, but i think same bug exist in 0.9.1 which is stable for pip version
So version v1.0.0 is released or it's still in development stage?

**Comment by stargame25** [comment]
And also i would like to ask to develop the way to login in without passing in the password, i'm building a website, which could handle multiple users, and i don't want passwords to leak on any stage, and would be cool if you include _send_login with custom password which encrypted on client side (with js or etc), i did it by myself, but if you can do this, please include in your todo list

**Comment by rossengeorgiev** [comment]
There are improvements to `WebAuth`. See https://github.com/ValvePython/steam/blob/master/CHANGES.md
There are pre-release version on pypi, https://pypi.org/project/steam/#history

You can help test the code and report any issues.
