### ISSUE TITLE
Event listener and blocking calls

### ISSUE THREAD

**Issue by byterussian** [ValvePython/steam#206]
Hello,

Imagine this code:
```
@client.on(EMsg.ClientPersonaState)
def handle_persona_state(result):
    time.sleep(20)

```

during those 20seconds I will lose PersonaState events sent by steam or they will get processed like a queue? If lost, best way to handle blocking calls(insert on db in my case) inside a decorated function with @client.on?

**Comment by rossengeorgiev** [comment]
You would not. Each callback is execute by spawning a new greenlet. I dont see why you would need to to sleep there, but if you must use a gevent compatible sleep, so that other greenlets can execute. Either `gevent.sleep()` or `SteamClient.sleep()`, or monkey patch `time.sleep()`.

**Comment by byterussian** [comment]
>  I dont see why you would need to to sleep there,

Was just an example, imagine to have to make an INSERT query in a db inside the function instead of a sleep function. Execution time could be few ms or few seconds :)

> , but if you must use a gevent compatible

Ok, so I need to find a way to connect to my db and send queries without blocking other greenlets. 

Thank you.
