### ISSUE TITLE
How to use multithreading?

### ISSUE THREAD

**Issue by justRoomboy** [ValvePython/steam#207]
I need to log in to several accounts and do certain actions with them. At first i try to do this with the help of the library threading, but this does not work (login only 1 account).I tried to use gevent.spawn (), but for this I need to use gevent.sleep (), due to which the steam connection is lost.

How i can do this?

**Comment by rossengeorgiev** [comment]
`SteamClient` uses gevent to do cooperative threads, so you just need to init multiple `SteamClient` instances to work with multiple accounts

**Comment by justRoomboy** [comment]
![image](https://user-images.githubusercontent.com/48877848/61578478-ffbe5180-ab10-11e9-9cca-2eaf2fa2bcfd.png)

Like this? But if I go to 30 account, I need to have 30 identical functions for each account.

**Comment by rossengeorgiev** [comment]
Yes, or you can do it all in a loop.

**Comment by justRoomboy** [comment]
How can write decorator and function in loop? Please write code for 1 function start_csgo. I not understand how make this
