### ISSUE TITLE
I'm trying to setup a basic chat messaging system

### ISSUE THREAD

**Issue by Gobot1234** [ValvePython/steam#210]
Hi, I'm trying to setup a system where I can send messages generated by a program and then sending them through this module

I am currently using:
```py
import gevent.monkey 
gevent.monkey.patch_socket()
 gevent.monkey.patch_ssl()

  from steam.client import SteamClient
 from steam.enums import EResult 
import logging  
# setup logging
 logging.basicConfig(format="%(asctime)s | %(message)s", level=logging.INFO) 
LOG = logging.getLogger()

  with open("Login details/setup.txt", "r") as f:  # reads your details     
    login = f.read()     
    login = login.replace("Token:\n", "")     
    login = login.replace(" # put your bot's token here\nShared Secret:\n", "")     
    login = login.replace(" # put your shared secret here\nUsername:\n", "")     
    login = login.replace(" # put your steam username here\nPassword:\n", "")     
    login = login.replace(" # put your steam password here", "")     
    login = login.split(' ')     
    token = login[0]     
    secret = login[1]     
    username = login[2]     
    password = login[3]     
    print('token is', token, '\nsecret is', secret, '\nusername is', username, '\npassword is', password)  

client = SteamClient() client.set_credential_location("Login Details/")  # where to store sentry files and other stuff

    # main bit 

LOG.info("Persistent logon recipe")
 LOG.info("-"*30)  

client.cli_login(username=username, password=password)    

@client.on("error") 
def handle_error(result):     
    LOG.info("Logon result: %s", repr(result))

  @client.on("channel_secured") 
    def send_login():     
    if client.relogin_available:         
        client.relogin()


  @client.on("connected")
 def handle_connected():     
    LOG.info("Connected to %s", client.current_server_addr)  


@client.on("reconnect") def 
    handle_reconnect(delay):     
        LOG.info("Reconnect in %ds...", delay)  


@client.on("disconnected") 
def handle_disconnect():     
    LOG.info("Disconnected.")      
    if client.relogin_available:         
        LOG.info("Reconnecting...")         
        client.reconnect(maxdelay=30)  


@client.on("logged_on") 
def handle_after_logon():     
    LOG.info("-"*30)     
    LOG.info("Logged on as: %s", client.user.name)     
    LOG.info("Community profile: %s", client.steam_id.community_url)     
    LOG.info("Last logon: %s", client.user.last_logon)     
    LOG.info("Last logoff: %s", client.user.last_logoff)     
    LOG.info("-"*30)     
    LOG.info("Press ^C to exit")

client.get_user(STEAM_ID).send_message(command) 
``` 
Where command is a message generated I would also like a way to check for responses and not have to use 2FA codes but first and foremost it doesn't send the message to the Steam ID. Thank you :)

**Comment by Gobot1234** [comment]
The problem is that nothing happens after typing in my 2FA code 
![image](https://user-images.githubusercontent.com/50501825/62322139-4494a180-b49c-11e9-848d-41732f97af40.png)

**Comment by rossengeorgiev** [comment]
It does, the program finishes running. You just never give a change to the event loop to run its tasks. Try adding `client.run_forever()` at the end.

**Comment by Gobot1234** [comment]
That worked thanks :)

I'm trying to send messages generated by some code above where this would be. If you want a look at the full code you can view it here: 
https://drive.google.com/open?id=1F62xGXmqUKEqjRCPOGVLhJvY59Opfb-K

**Comment by Gobot1234** [comment]
Although it seems to connect and then almost instantly disconnect 
![image](https://user-images.githubusercontent.com/50501825/62325520-b8867800-b4a3-11e9-81d5-33ca9660d0a2.png) which I don't really understand.

**Comment by Gobot1234** [comment]
Is there anything wrong with the steam implementation as now it doesn't appear to work? It will ask for your 2FA code but it wont log in.

**Comment by Gobot1234** [comment]
```py
@client.on("chat_message") 
def handle_receive(user):     
    if user == SteamUser(id=bot64id):         
        print('working')```
Is this how to check for steam messages from a certain user?

**Comment by Gobot1234** [comment]
Hey, I was wondering if there would be a better way to contact you than the IRC channel.

**Comment by rossengeorgiev** [comment]
`SteamUser` is not intended to be initialized like that. You can see what properties it has at https://steam.readthedocs.io/en/latest/api/steam.client.user.html

Just compare the steam ids `user.steam_id == bot64id`.

Yes, you can send the message that way. Or you can implement the message command yourself as `get_user()` does cache the `SteamUser` instance, but if you don't keep it referenced somewhere it will get destroyed. For example, `FriendList` will keep a references of the `SteamUser` instances, so `get_user()` wont initialize it every time. You can look at the docs for details.

**Comment by Gobot1234** [comment]
Noted thank you for the response.

**Comment by Gobot1234** [comment]
Ok so I've now got another issue with my code: 
![image](https://user-images.githubusercontent.com/50501825/64877365-27c9bd00-d649-11e9-8111-48e9b71c7e42.png)
This doesn't now send messages via steam, there is no error or traceback, it just won't send. I was told to take this to you, as the discord side of this code is fine and should be correct and there shouldn't be any reason it doesn't work

The main part of the code is:
```py
self.bot.client.get_user(self.bot.bot64id).send_message(content) ```
which was converted from:
```py
client.get_user(bot64id).send_message(content) ```

If you need more info or context the file is here: 
[The login](https://gist.github.com/Gobot1234/5227d0de4c530f5503484939363c93d0)
[The Steam Side](https://gist.github.com/Gobot1234/bff07e50abc631f8db1d35e294ec0f68)

Thanks.

**Comment by Gobot1234** [comment]
I've narrowed down the issue to be the `.send_message(str)` part as printing the output of `self.client.get_user(self.bot.bot64id)` returns a Steam user instance, on the next line not sending the message to that user.

**Comment by Gobot1234** [comment]
I've fixed the issue, I think it was to-do with the way I was naming `client` between class vars
