### ISSUE TITLE
Depot info missing from product info

### ISSUE THREAD

**Issue by pistol-whip** [ValvePython/steam#212]
I was trying to receive the product info about the app id 1042420 but the depot section is missing from the response.

The account owns the game and I am able to download it using the normal Steam client and SteamCMD. SteamDB also has the depot info available. 

Is there anything I am missing or what could be the reason for this?

**Comment by rossengeorgiev** [comment]
Hi @pistol-whip, you need an access token.

```
access_token = client.get_access_tokens([1042420])['apps'][1042420]
info = client.get_product_info([{'appid': 1042420, 'access_token': access_token}])
```

**Comment by pistol-whip** [comment]
Hello @rossengeorgiev, thank you very much.
