### ISSUE TITLE
The program closes by itself

### ISSUE THREAD

**Issue by justRoomboy** [ValvePython/steam#215]
Sometimes a program closes by itself without any exceptions. Has anyone come across this?

**Comment by Gobot1234** [comment]
I've had this are you getting a heap error?

**Comment by justRoomboy** [comment]
No, i not get any error

**Comment by Gobot1234** [comment]
I get an exit code after I run it for like 30 mins (3.6.8) maybe about 2 hours (3.7.4) I think the issue is with threading. Although I may be wrong.

**Comment by rossengeorgiev** [comment]
There is no information here that can be used to debug your issue. No platform, no package versions, no logs, nothing.

**Comment by Gobot1234** [comment]
I'm on the most recent stable version, 0.9.1, Windows 10 64 bit but I don't know how to find logs for it. 👍
