### ISSUE TITLE
client.licenses returns empty

### ISSUE THREAD

**Issue by wynick27** [ValvePython/steam#217]
After login, I tried to access license but it's empty. 
```python
>>> from steam.client import SteamClient
>>> c = SteamClient()
>>> c.cli_login()
>>> c.licenses
{}
```

**Comment by rossengeorgiev** [comment]
The license message might have not arrived immediately after login. Try adding a second delay `c.sleep(1)` before checking the licenses dict.

**Comment by wynick27** [comment]
That solves the problem. Thanks.

**Comment by rossengeorgiev** [comment]
Ideally, you want to wait for that specific message.

Inline:
```python
c.wait_event(EMsg.ClientLicenseList)
```
Or as a callback:
```python
@c.on(EMsg.ClientLicenseList)
def my_func(message):
    pass
```
