### ISSUE TITLE
Package subscriptions

### ISSUE THREAD

**Issue by pistol-whip** [ValvePython/steam#221]
I am currently in a situation where I want to download server specific files. Some of the depots/apps require ownership and some don't but are only included in the "Anonymous Dedicated Server Comp" with no other way to get access to it. 

I made a workaround by running an anonymous client and an authenticated client in different processes and retrieving the auth tokens async. This however is a suboptimal solution.

Is there another, better way to implement this?

The app in question is 258550

Thanks in advance

**Comment by rossengeorgiev** [comment]
Hi there, that doesn't sound right. You will either need anon or normal account to access, never both at the same time.

All depots for `258550` are included in `Anonymous Dedicated Server Comp` package https://steamdb.info/app/258550/subsdebug/

Are these not enough to run the server, and you need other apps or what?

**Comment by pistol-whip** [comment]
I have to access multiple apps. Some require ownership and some (like `258550`) don't. 

`258550` is a bit of a weird one too, it is not granted to accounts which own the base app and only available to anon accounts. I tried claiming the packages, just to see if that works but also no success.

So that together would require me to hold up 2 instances of SteamClient, one with a logged in account for all the apps and workshop items wo require app ownership and then another one for those that only work with anon. And thats what I am wanting to get around but haven't succeded in finding a passable solution.

**Comment by rossengeorgiev** [comment]
I see. There is no way to around that.
