### ISSUE TITLE
Using same login token and secrets as official Steam client

### ISSUE THREAD

**Issue by JuniorJPDJ** [ValvePython/steam#222]
Hi guys, thank you for amazing job!
Is it possible to use official steam's secrets?
I would like to see password-less login when official client is in "remember me" state.

**Comment by rossengeorgiev** [comment]
Possibly, if you can gather all necessary pieces of information from the Steam folder. This is not a feature available in this package, and will likely never be.

**Comment by JuniorJPDJ** [comment]
Ok, but can you tell me at least what am I looking for?

**Comment by rossengeorgiev** [comment]
There is no valid use case for this, besides stealing a logged-in steam session.  I cannot help with that.

**Comment by JuniorJPDJ** [comment]
I'm trying to not log-in twice. I'm creating account changer which would also maintain information about owned games (for dynamic account switching - start account which owns started game etc) and game ranks.

**Comment by xiao-e-yun** [comment]
if u only in windows
u can use 
`win+r` => regedit

<your_PC\>\HKEY_CURRENT_USER\SOFTWARE\Valve\Steam

if u logged ,it will work
`AutoLoginUser <username\>`

if u use pywinauto GUI tools ,
u don't need carry RememberPassword's check box
`RememberPassword <1 or 0\> #steam.exe -login <=not work`

i try it on this project
https://github.com/xiao-e-yun/better_Steam_tool

**Comment by JuniorJPDJ** [comment]
I'm not sure I understand what you mean @xiao-e-yun

**Comment by xiao-e-yun** [comment]
you can change your regedit 
![image](https://user-images.githubusercontent.com/67814228/119531895-f4947680-bdb6-11eb-9708-23f48b8378c9.png)

if steam  rememberPassword is true
just restart game it will login AutoLoginUser's value

**Comment by JuniorJPDJ** [comment]
That's what I already know.
I'd like to reuse this login data with python using this library without entering 2FA codes again.

**Comment by xiao-e-yun** [comment]
I don't think is possible
maybe u can try it
