### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by woctezuma** [ValvePython/steam#223]
The [doc ](https://steam.readthedocs.io/en/latest/user_guide.html#calling-an-endpoint) features the following import for the WebAPI:

```python
from steam.steamid import WebAPI
```

![Typo](https://i.imgur.com/kiHoeIl.png)

Instead, it should be:

```python
from steam.webapi import WebAPI
```

**Comment by rossengeorgiev** [comment]
Thanks
