### ISSUE TITLE
Block people

### ISSUE THREAD

**Issue by Snavellet** [ValvePython/steam#225]
How to block people?

**Comment by rossengeorgiev** [comment]
Not sure what Steam uses these days, its probably a unified message. The block is essentially a friendship relationship, and there is limit how many accounts can be blocked. Best thing to do is nethook the client and see what happens when you block someone.

**Comment by Snavellet** [comment]
Thanks, I found it, it's ```EMsg.ClientSetIgnoreFriend```.

**Comment by Snavellet** [comment]
`EMsg.ClientSetIgnoreFriend` it returns !! NO BODY !! when I printed the body

**Comment by rossengeorgiev** [comment]
Looks like there is no protobuf for it. Must be have been moved to unified messages. Try:

https://github.com/ValvePython/steam/blob/1a84d653ff36235151e6930ba0581a8cdde8349f/protobufs/steammessages_player.proto#L186-L193

```python
resp = client.unified_messages.send_and_wait("Player.IgnoreFriend#1", {"steamid": 1111111111})
```

**Comment by Snavellet** [comment]
```py
    def block_user():
        resp = client.unified_messages.send_and_wait("Player.IgnoreFriend#1", {"steamid": 76561198840991984})
        print(resp)

    block_user()```

```

**Comment by Snavellet** [comment]
```KeyError: ('Player.IgnoreFriend#1', False)
2019-11-30T13:57:38Z <Greenlet at 0x1f9d30bf8c8: logged_on> failed with KeyError
```

```KeyError: ('Player.IgnoreFriend#1', False)
2019-11-30T13:57:38Z <Greenlet at 0x1f9d30bf8c8: logged_on> failed with KeyError
```
I got an error.

**Comment by rossengeorgiev** [comment]
Looks like v0.9 doesn't have the protos. I would try the v1.0.0.

**Comment by Snavellet** [comment]
It returns none now

**Comment by rossengeorgiev** [comment]
I've tried this and it works. The user gets blocked.

```python
client.send_um_and_wait("Player.IgnoreFriend#1", {"steamid": 123456789})
```
