### ISSUE TITLE
How to grab richpresence KV from EMsg ClientRichPresenceInfo?

### ISSUE THREAD

**Issue by sadlyfell** [ValvePython/steam#226]
Hi, I tried to grab rich presence info from targeted user by calling `EMsg ClientRichPresenceRequest` and it should return the requested data inside `EMsg ClientRichPresenceInfo` 
But my `rich_presence_kv` always return empty `b''` even if the targeted user already in a dota2 match.

Code:
```
proto_msg = MsgProto(emsg.EMsg.ClientRichPresenceRequest)
proto_msg.body.steamid_request.extend([76561198138376606])
resp = client.send_message_and_wait(proto_msg, emsg.EMsg.ClientRichPresenceInfo)
LOG.info(repr(resp))
```

Result:
```
rich_presence {
  steamid_user: 76561198138376606
  rich_presence_kv: ""
}
```

**Comment by sadlyfell** [comment]
Solved it by adding targeted header manually
```
proto_msg = MsgProto(emsg.EMsg.ClientRichPresenceRequest)
proto_msg.header.routing_appid = 570
proto_msg.body.steamid_request.extend([76561198138376606])
resp = client.send_message_and_wait(proto_msg, emsg.EMsg.ClientRichPresenceInfo)
LOG.info(repr(resp))
```

This is also capable to track offline/invisible users. Looks like the current implementation with `request_persona_state(steam_ids, state_flags=863)` not be able to track offline/invisible user while playing.

**Comment by rossengeorgiev** [comment]
If its a user on the friend list, you can get a `SteamUser` instance via `get_user(steamid)` and access `rich_presence` attribute to get the key-values as a `dict`.

https://steam.readthedocs.io/en/latest/api/steam.client.html#steam.client.SteamClient.get_user
https://steam.readthedocs.io/en/latest/api/steam.client.user.html#steam.client.user.SteamUser.rich_presence
