### ISSUE TITLE
Can't change password

### ISSUE THREAD

**Issue by TSecretT** [ValvePython/steam#230]
Hi, I have successfully managed to send password change request to an email, however i noticed that when I try `client.change_password(oldPassword, newPassword, code)`, user goes offline and I get `<EResult.Timeout: 16> ` respond. What could be the problem?

**Comment by rossengeorgiev** [comment]
Hi @TSecretT, these functions have likely been deprecated by Valve. All this is now done through the website rather than steam protocol. https://help.steampowered.com/en/wizard/HelpWithLoginInfo

**Comment by TSecretT** [comment]
Thanks for the answer, but im still stuggling understanding the APIs, so is it possible to change the password somehow using your repository?

**Comment by rossengeorgiev** [comment]
There is not.
