### ISSUE TITLE
change profile picture

### ISSUE THREAD

**Issue by SirWindfield** [ValvePython/steam#232]
I couldn't find any way to change the user's profile picture. Is this currently supported?

**Comment by rossengeorgiev** [comment]
The package provides no such function at the moment. However, you can authenticate with steamcommunity and implement the avatar upload functionality if you wanted to.

**Comment by Hexiro** [comment]
how would one go about this? @rossengeorgiev

**Comment by rossengeorgiev** [comment]
An attempt to do this is made in #290
