### ISSUE TITLE
Can client.get_changes_since() triggers be caused by price updates?

### ISSUE THREAD

**Issue by vBubbaa** [ValvePython/steam#233]
I noticed in the output of `client.get_product_info([appid])` that it doesn't provide the games price however if the game triggers a change in `client.get_changes_since([appid])`, can it mean that the price has changed? I am trying to use this library to monitor game changes including the games prices.

Thanks!

**Comment by rossengeorgiev** [comment]
Hi, I think the you do get changelist for when a price changes. I think the only way to get the price is via the web store.

**Comment by vBubbaa** [comment]
Thanks Rossen, I have a way of getting the price, I was just curious to know if the changelist is triggered by price updates. Also is there a list somewhere that I can see or figure out the various triggers that can cause a "change" on the changelist? Thanks for your work in porting over Steamkit.

**Comment by rossengeorgiev** [comment]
I think it does trigger a changelist, but I won't know. There is no list, you will have to find out for yourself
