### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by owoki** [ValvePython/steam#234]
How can i use proxy with this libary on login ?

**Comment by rossengeorgiev** [comment]
Hi, it is not possible to configure a proxy. However, you can implement your own connection class that provides proxy transport. See https://github.com/ValvePython/steam/blob/master/steam/core/connection.py

**Comment by owoki** [comment]
> 
> 
> Hi, it is not possible to configure a proxy. However, you can implement your own connection class that provides proxy transport. See https://github.com/ValvePython/steam/blob/master/steam/core/connection.py


i edit webauth.py but i get an error "json". In code used requests lib and Session i add  proxy config for session func but not worked. Can I set a proxy for the entire python program? Or how can I do this ?

**Comment by rossengeorgiev** [comment]
Possibly your proxy is bad or something. It's not really a support feature. See http://2.python-requests.org/en/v1.1.0/user/advanced/#proxies

**Comment by olehsamoilenko** [comment]
I'm also interested of proxy. Currently I'm using torrequest for scrapping data from the market. It's pretty similar with requests in use. It will be cool if steam authentication will have a proxy option too.

**Comment by rossengeorgiev** [comment]
@olehsamoilenko, do you mean `WebAuth` class? It's still just a `requests.Session`.

```python
web = WebAuth()
web.session.proxy = {
  "http": "...:3128",
  "https": "...:3128",
}
