### ISSUE TITLE
webauth urls

### ISSUE THREAD

**Issue by TSecretT** [ValvePython/steam#236]
Hi, I am looking for a list of all urls, or a way to find them by myself to interract with steam.

In on of the examples, we send a POST request to `session.get('https://store.steampowered.com/account/history')`, and if I insert this URL into a browser, it opens the page stays the same, however when i enter `'https://steamcommunity.com/profiles/{}/edit'.format(user.steam_id)`, the URL changes.

So how can I get the url that i should send requests to?

Also, how do I know which `data` keys and values I should send with POST request?
```
status_code = session.post('https://steamcommunity.com/games/970610/selectAvatar',
    data={
    'selectedAvatar': random.randint(0,25),
    'sessionid': user.session_id
```
Thank you

**Comment by TSecretT** [comment]
no clue?

**Comment by rossengeorgiev** [comment]
Such list doesn't exist as far as I know.
