### ISSUE TITLE
Question regarding games_played()

### ISSUE THREAD

**Issue by TSecretT** [ValvePython/steam#238]
Im trying to use a games_played() to play CSGO (id 730), but for some reasons none of codes worked for me

I have tried with `client.games_played([730])`, didnt work. Tried adding `run_forever()`, didnt work as well. 
Also tried the code that has been mentioned in of the other issues:
 `client.send(MsgProto(EMsg.ClientGamesPlayed),
            {'games_played': [
                {'game_id': 15190414816125648896, 'game_extra_info': 'SOME GAME NAME'},
                ]
            })`

**Comment by rossengeorgiev** [comment]
If you own the app, that is how you indicate to Steam that you are playing the app. Not sure what you are trying to do exactly. I need more context or/and code to give a better answer

**Comment by TSecretT** [comment]
Basically I want to simulate playing several games at the same time, so my played time gonna increase :p

**Comment by rossengeorgiev** [comment]
Something like this should work:

```python
from steam import SteamClient

s = SteamClient()
s.cli_login()

while True:
  s.game_played([730, 123, 345])
  s.wait_event(s.EVENT_DISCONNECTED)
  if s.relogin_available:
    s.reconnect()
    s.relogin()
  else:
    print("Failed to reconnect")
    break
```

**Comment by TSecretT** [comment]
Works like a charm, thanks
