### ISSUE TITLE
How do you run this in parallel of other things

### ISSUE THREAD

**Issue by ZChenzy** [ValvePython/steam#239]
Hi, I am quite new to Python and I am not sure what the pattern is in implemented a http server that allows me to use and create apis that allows me to interface with the Client and Dota since client.run_forever() is blocking the main thread. Does anyone have any examples?

**Comment by rossengeorgiev** [comment]
Hi, have you looked at https://github.com/ValvePython/steam/tree/master/recipes/2.SimpleWebAPI ?

**Comment by rossengeorgiev** [comment]
Assuming this issue was resolved.
