### ISSUE TITLE
Compatibility for different UI Modes?

### ISSUE THREAD

**Issue by 2Eggsss** [ValvePython/steam#242]
Hey there,

I was looking through the API documentation but I couldn't find anything similar to SetUIMode which is available on node-steam-user. Do you have any ideas if it'll be ever added? Is there any alternative to do it through EMsg's at all?

Thanks!

**Comment by rossengeorgiev** [comment]
There isn't one, so just send the message:

```python
client.send(EMsg.ClientCurrentUIMode, {
'uimode': 4
})
```
https://github.com/DoctorMcKay/node-steam-user/blob/1f8761fba510b9f306612d861c51d5f49e1bf0e7/resources/EClientUIMode.js#L2-L8

**Comment by 2Eggsss** [comment]
Hey, that's awesome thanks! I look forward to it's implementation.
