### ISSUE TITLE
multiple persona_state_flags?

### ISSUE THREAD

**Issue by 2Eggsss** [ValvePython/steam#244]
Hey there,
I made a new issue as this one is not linked to my previous one.
Basically I'm trying to do multiple persona_state_flags with my client.change_status but it simply doesn't work. I can do singular state flags but if I do more than one, it just starts complaining about how 'int' object has no attribute 'extend'...
Do you have any ideas or is this not supported and I will also have to rely on a proto message for this as well?

Thanks!

**Comment by rossengeorgiev** [comment]
https://steam.readthedocs.io/en/latest/api/steam.enums.html#steam.enums.common.EPersonaStateFlag

If you look at the values they are powers of 2. That is because each flag represented as a single bit. To combine multiple flags you either `add` or `bitwise OR` them together.

```python
flags = EPersonaStateFlag.HasRichPresence | EPersonaStateFlag.InJoinableGame
# or
flags = EPersonaStateFlag.HasRichPresence
flags |= EPersonaStateFlag.InJoinableGame
```
To check for a flag:

```python
(flag & EPersonaStateFlag.HasRichPresence) == EPersonaStateFlag.HasRichPresence
# or
(flag & EPersonaStateFlag.HasRichPresence) != 0
```

**Comment by 2Eggsss** [comment]
Thanks for the help, it seemed to work with all the values present in the API docs you linked...

In SteamKit, there are some new EPersonaStateFlag values such as RemotePlayTogether and LaunchTypeCompatTool, is there a way to implement them as well? As currently there is no way for me to utilize them.

Thanks once again!
