### ISSUE TITLE
get_server_list() always returns TypeError

### ISSUE THREAD

**Issue by impaex** [ValvePython/steam#249]
I tried running this code:
```py
from steam import client
for x in client.builtins.gameservers.SteamGameServers.get_server_list(r'\appid\730\white\1'):
  print(str(gs.a2s_info(x)))
```
No matter what I do, line 2 returns the following error:
```py
TypeError: get_server_list() missing 1 required positional argument: 'filter_text'
```

I would love to know why it doesn't work.

**Comment by rossengeorgiev** [comment]
Yes, it's a instance method, not a static method. You need to create a `SteamClient` instance, and call `client.gameservers.get_server_list(...)`
