### ISSUE TITLE
Provide example for simple non-authenticated workflows

### ISSUE THREAD

**Issue by EEwing** [ValvePython/steam#250]
I'm looking for examples on how to do things like getting a steamid from various sources. There are examples in the docstrings for SteamID, but a central example to explain both SteamID and steamid.from_url would be great.

I'm also trying to get account information like username, avatar, and whatever else information the accounts have available to them without having to authenticate my steam client (assuming of course that their profile info is public). For instance, grabbing all of that data from a discord bot that doesn't support per-user authentication. I haven't been able to figure out how to do that yet at all, so if you could explain how to take a SteamID and turn it into a user object that I could get the avatar information from, that would be great.

Thanks!

**Comment by rossengeorgiev** [comment]
`SteamID` is simply unique identifier for accounts.

The examples show pretty much all cases. `SteamID` can be initialized with the various formats, which are used across Steam and Valve's games. It provides a single consistent interface.

`from_url` is a convenience method to initialize a `SteamID` from various URL, such as the community profile ones, and other. All accepted urls are listed in the docstrings, everything else will result in a invalid `SteamID` that you can test for with `SteamID.is_valid()`

There is no functionality to collect the various information you mention. It is up you to implement it.
