### ISSUE TITLE
2 bots in one time

### ISSUE THREAD

**Issue by re-fMouse** [ValvePython/steam#252]
I'm trying make 2 bots(discord&steam) working in 1 script to interact with each other, i found how to add loop into discord bot, so it can work with another bot, i tried add it to the loop, because steambot shows, that he is online, but he not react and not working, what can i do to add him into the loop and let him work? adding client.sleep() gives an error message

```
result = clientsteambot.login(config.USERNAME, config.PASSWORD)
print(str(result))

loop = asyncio.get_event_loop()
loop.create_task(clientdisordbot.start(config.TOKEN))
loop.create_task(clientsteambot.sleep(1))
loop.run_forever()
```

**Comment by fMouse-creator** [comment]
full code, where steambot runs and is online, but it doesn’t respond to anything

```
import gevent.monkey
gevent.monkey.patch_socket()
gevent.monkey.patch_ssl()

from discord.client import Client
import asyncio
import config

from steam.client import SteamClient
from steam.enums import EResult

client = SteamClient()
clientdis = Client()

#Steambot
@client.on('connected')
def connected():
    print('Connected steambot\n')

@client.on('chat_message')
def handle_message(user, message_text):
    print('Got message: ' + str(message_text))

#Discordbot
@clientdis.event
async def on_ready():
    print('Discord bot ready')


@clientdis.event
async def on_message(msg):
    print('Got message: ' + str(msg))

#steambot
def start_steam_bot():
    print("Logining started")
    print("-"*20)
    result = client.login(config.USERNAME, config.PASSWORD)
    print('Steam bot login result = ' + str(result))

start_steam_bot()

loop = asyncio.get_event_loop()
loop.create_task(clientdis.start(config.TOKEN))
loop.run_forever()
```

**Comment by int3l** [comment]
You can't mix asyncio with gevent (which is libev/libuv - an other event loop basically).
I use multiprocessing for that :)

**Comment by rossengeorgiev** [comment]
Hi @int3l, I'd be interested to know how apply multiprocessing as gevent apparently doesn't play well with it.

**Comment by int3l** [comment]
Hi @rossengeorgiev :)
I will soon share my combo bot (steam + discord) with you. It is based on your library and the discord.py one.

I just need some time to polish it and make it configurable, so it can be distributed nicely.
But basically - I have master process that invokes the two bots with `multiprocessing.Process` or `multiprocessing.pool.Pool` (pretty standard stuff).

For communication between the two bots you can use `multiprocessing.Manager` and `multiprocessing.Queue` or anything else like `pynng`.

**Comment by rossengeorgiev** [comment]
I see. It would be interesting to come up with a generic pattern for integrating gevent based code with other projects.

**Comment by int3l** [comment]
@rossengeorgiev има ли възможност да се свържа по някакъв друг начин с теб - еmail, Discord (чрез общ сървър или DM), Steam?

**Comment by Gobot1234** [comment]
I have an old bot that works with discord.py if you want to take a look https://github.com/Gobot1234/tf2autocord (it kinda sucks now and it's pretty unreadable)

**Comment by Gobot1234** [comment]
The main jist is to have a function containing the SteamClient instance and your listeners, then to run that with asyncio.AbstractEventLoop.run_in_executor(None, the_function_as_a_callable, *args)

**Comment by re-fMouse** [comment]
I resolve my problem 10 days ago, just used threading. when he getting messaage in the discord channel, he send this message me to the steam

```
from discord.ext import commands
import threading
import time
import asyncio
import config
from steam.client import SteamClient
from steam.enums import EResult

client = SteamClient()


#Steambot
@client.on('connected')
def connected():
    print('Connected steambot\n')

@client.on('auth_code_required')
def auth_code_prompt(is_2fa, mismatch):
    if is_2fa:
        code = input("Enter 2FA Code: ")
        client.login(two_factor_code=code, **LOGON_DETAILS)
    else:
        code = input("Enter Email Code: ")
        client.login(auth_code=code, **LOGON_DETAILS)

@client.on('chat_message')
def handle_message(user, message_text):
    print('Got steam message: ' + str(message_text) + ' from: ' + user.name +' with steamid:' + str(user.steam_id))
    user.send_message('Command not found, if there anything wrong, contact with me')

LOGON_DETAILS = {
    'username': config.USERNAME,
    'password': config.PASSWORD,
}

class MyBot(commands.Bot):
    async def on_ready(self):
        print(f'Ready {self.user}:{self.user.id}')
    async def on_message(self, message):
    	print('Got discord message: ' + message.content + ' from: ' + str(message.author.nick) +'')
    	client.get_user(config.STEAMID).send_message('Got discord message: [' + message.content + '] from: [' + str(message.author.nick) +']')


def run_bot_in_thread():
    # Important to make an event loop for the new thread
    asyncio.set_event_loop(asyncio.new_event_loop())
    bot = MyBot(command_prefix='!')
    bot.run(config.TOKEN)

threading.Thread(target=run_bot_in_thread, daemon=True).start()

result = client.login(**LOGON_DETAILS)
print('Steam bot login result = ' + str(result))
client.run_forever()
```
