### ISSUE TITLE
Querying servers

### ISSUE THREAD

**Issue by OverLordGoldDragon** [ValvePython/steam#256]
Does the API enable querying server (`View -> Servers`) info? More specifically, `Players` data for individual servers:

![image](https://user-images.githubusercontent.com/16495490/80910009-d425f400-8d3d-11ea-8c71-4dbf548c3ead.png)

**Comment by rossengeorgiev** [comment]
You can either query servers via the legacy hlmaster: https://steam.readthedocs.io/en/stable/api/steam.client.builtins.html#module-steam.client.builtins.gameservers  

Or via Steam: https://steam.readthedocs.io/en/stable/api/steam.game_servers.html

**Comment by OverLordGoldDragon** [comment]
Perfect, works; will still reinstall as suggested in other thread
