### ISSUE TITLE
No module named 'eventemitter', 'google'

### ISSUE THREAD

**Issue by OverLordGoldDragon** [ValvePython/steam#257]
```
Traceback (most recent call last):
  File "C:\steam\main.py", line 3, in <module>
    from steam.client.builtins import gameservers as gs
  File "D:\Anaconda\envs\steam\lib\site-packages\steam\client\__init__.py", line 25, in <module>
    from eventemitter import EventEmitter
ModuleNotFoundError: No module named 'eventemitter'
```
Anaconda virtual environment, Win 10 OS. Looks a missing dependency from `requirements.txt`. Problem solved via `pip install eventemitter`.

Same deal for `google`, solved via `pip install google-api-python-client`.

**Comment by rossengeorgiev** [comment]
Those are incorrect. Definitely uninstall them.

 If you are using the `client` part of the `steam` package you need to install via the client extra. See https://github.com/ValvePython/steam#install

`pip install steam[client]`

The buildins are not indented to be imported directly. They are made available on the `SteamClient` instance.

**Comment by OverLordGoldDragon** [comment]
`pip install steam[client]` does work, my mistake.

**Comment by rossengeorgiev** [comment]
A very simple example:

```python
client.SteamClient()
client.cli_login()
servers = client.game_servers.get_server_list(r'\appid\730')
print(servers)
```

**Comment by OverLordGoldDragon** [comment]
@rossengeorgiev Made a data stream to a .csv of player count for two servers of a particular game - the querying step is remarkably simple, well done on the API.
