### ISSUE TITLE
How to get list of package IDs and apps

### ISSUE THREAD

**Issue by shakeyourbunny** [ValvePython/steam#263]
I read the documentation thoroughly, but how do I get a list of owned package IDs (subs) and app ids?

My goal is to get my owned packages (where the appids are listed).

Can somebody give me an example how to write this with this package?

**Comment by rossengeorgiev** [comment]
See https://github.com/ValvePython/steam/blob/aba4942a090211f5e0ff8ec9dd801dcf77f9c24d/steam/client/cdn.py#L469-L485
