### ISSUE TITLE
Read messages from GameCoordinator via SteamClient only

### ISSUE THREAD

**Issue by ram-gopal-rao** [ValvePython/steam#267]
Hello,

Before I begin explaining my question, I'd like to thank everyone who's behind this project. It's an amazing effort!

Is it possible to read incoming GameCoordinator messages without actually launching a game (dota)? The idea is to physically launch the game on my machine and use SteamClient to read messages from GC. Example cases: Know when a friend has invited you to a party, when a ready check has been requested, when a game is found etc. 

I do know that sending messages to GC is a bit far fetched without actually using DotaClient, but I'd just like to know if it's possible to read  messages coming from GC using only SteamClient

Thanks in advance!

**Comment by rossengeorgiev** [comment]
No, you can't. The module implements the steam protocol. The can be only one session that has access to GC, and that would be the one playing the game. Look into https://github.com/SteamRE/SteamKit/tree/master/Resources/NetHook2
