### ISSUE TITLE
SessionID does not return properly for SteamClient

### ISSUE THREAD

**Issue by sinister** [ValvePython/steam#270]
Hi, 

steam.client.SteamClient.sessionid does not return the actual sessionid whilst steam.webauth.WebAuth.sessionid does. The SteamClient sessionid that is returned is an int number whilst the WebAuth one is the (as expected) string.

**Comment by rossengeorgiev** [comment]
That is correct. `session_id` for web is a cookie and therefore a `str`, which different from steam protocol `session_id`, which is number. Web is generated by client, and steam protocol by the backend.
