### ISSUE TITLE
SetPersonaName available?

### ISSUE THREAD

**Issue by csm10495** [ValvePython/steam#274]
Hi,

Is there a way to call SetPersonaName() as specified here: https://partner.steamgames.com/doc/api/ISteamFriends ?

I tried doing something like: 

```
client.change_status(player_name='testing123')
```

but that didn't seem to work.

**Comment by rossengeorgiev** [comment]
No, this package is complete re-implementation of the Steam protocol. `change_status()` will work to change the name.

```python
print(client.user.name)
client.change_status(player_name="funky new name")
client.sleep(1)
print(client.user.name)
```

**Comment by csm10495** [comment]
@rossengeorgiev , it doesn't seem to always work. Also client.user.name doesn't always reflect the set player name:

```
>>> client.change_status(player_name='testing123456789')
>>> client.user.name
'testing123'
>>> client.change_status(player_name='testing12345678910')
>>> client.user.name
'testing123'
>>>
```

Oddly on steam's website the change is more often reflected than in Python via the above. Though sometimes it still doesn't update there either.

Is there a way to check if the request worked or not?

**Comment by rossengeorgiev** [comment]
You have fundamental misunderstanding how the library works. When you call `change_status`, all you are doing is queuing up a packet to be sent. The call doesn't implicitly yield to the event loop, and the code that sends the packet is yet to run. Any IO, `sleep()`, `idle()`, `wait_msg`, etc pauses the current code and lets other code run. `client.user` get updated once the Steam backend responds with packet notifying the name has changed.

I suggest reading up on gevent first as that is how `SteamClient` is implemented

**Comment by csm10495** [comment]
Seems to work after calling .idle(). 

I'd highly recommend having an example that uses ```sleep()``` or ```idle()``` to wait for a task to complete.  

Closing.

**Comment by rossengeorgiev** [comment]
You can also wait for the specific message that updates the user object, which would be the optimum way of doing it. Calling `idle()` doesn't guarantee that that message would arrive before `idle()` returns.
