### ISSUE TITLE
Clan SteamIDs from account id fails

### ISSUE THREAD

**Issue by Gobot1234** [ValvePython/steam#275]
### Summary

When constructing a SteamID for a clan from its 32 bit ID, its type and instance properties are set to `EType.Individual` and `0` respectively causing the `as_64` property to return an incorrect value. The result should obviously be the same as the initial 64 bit ID.

### Reproduction Steps

```py
>>> from steam.steamid import SteamID

>>> SteamID(id=SteamID(103582791466991873).id)
... 76561197997736193
```

**Comment by rossengeorgiev** [comment]
When you only provide `accountid` part of the a steamid, then `SteamID` assumes `EType.Individual`. There is not way to magically conjure the remaining 32bits of steamid.
