### ISSUE TITLE
Using WebAuth method to skip secondary login page?

### ISSUE THREAD

**Issue by dylan-park** [ValvePython/steam#280]
I'm utilizing this library to provide steam login credentials for use on a separate website that requires steam login to download files.

I get as far as fully authenticating and getting a session returned, then use that session to make a get request. But instead of just using the steam auth session to download the file I'm first faced with a sudo login page where I am definitely logged into steam but I must click a secondary login button in order to confirm the login. The page looks like the image below.

![636pE.png](https://user-images.githubusercontent.com/5841057/89047008-63c64900-d313-11ea-8b1f-052c0a66c59a.png)

I've tried a couple simple fixes to no avail yet. Before I do something kinda drastic like making a selenium session and trying to pass auth cookies back and fourth just to click the button, I wanted to make sure I was not missing something in the docs that could get past this point? I've read through them and don't really see any webauth tools that assist in this issue.

**Comment by rossengeorgiev** [comment]
`WebAuth` is the equivalent of going to `store.steampowereded.com ` and login in with your steam credentials. The picture shows openid login page, where a third-party site uses Steam as identity provider. That allows users to login to the third-party site without disclosing their credentials to third-party. If you encountering issues with `WebAuth` please include relevant code to debug further.

**Comment by dylan-park** [comment]
Okay, I think I misunderstood the powers of webauth then. I was under the impression openid worked along side steam web authentication. I'm not experiencing any specific bug using webauth on its own, but was just trying to use it for openid as well. Knowing that, I'll just have to handle openid separately. Apologies for the misunderstanding.
