### ISSUE TITLE
Is it possible to connect to game servers using this?

### ISSUE THREAD

**Issue by SargeraMC** [ValvePython/steam#282]
Hello, don't know if this is the right place, but would you be able to connect to a game server using this?
For example Ark Survival servers, if you knew the address you need to connect from.
I need this to be able to see the profiles of people connected on server. Thanks for any help!

**Comment by rossengeorgiev** [comment]
No. Talking to game servers would depend on game, and it is a different protocol. This only talks to Steam and Steam's Game Coordinators.
