### ISSUE TITLE
Applied example: server logger

### ISSUE THREAD

**Issue by OverLordGoldDragon** [ValvePython/steam#283]
General-purpose enough to serve as a mini-app; could feature it in your examples if suitable: https://gist.github.com/OverLordGoldDragon/b9507ad4cf81c22048985192b757a1de

**Comment by rossengeorgiev** [comment]
Thanks. I would like to keep the recipes simple and specific to help illustrate use better. I think this a tad more complicated, just like  https://github.com/ValvePython/steamctl is. I don't have more complicated examples, but if I gather enough I may create a section to with links to them.

**Comment by OverLordGoldDragon** [comment]
@rossengeorgiev Understandable; I'd recommend a "gallery" of examples showcasing what can be done with the package, just images of results, with links to the code for those interested - just like [Dash](https://dash-gallery.plotly.host/Portal/).
