### ISSUE TITLE
Error Duplicate request

### ISSUE THREAD

**Issue by 0xearl** [ValvePython/steam#296]
Hello, I am having getting this error "steam.guard.SteamAuthenticatorError: Failed to add authenticator. Error: <EResult.DuplicateRequest: 29>"

i already have steam authenticator on my phone but sadly my phone died but i got a backup codes (which i am using to authenticate to this script)

or do still have to do the sa.add() if i already have authenticator in phone?

**Comment by rossengeorgiev** [comment]
That means there is already an authenticator, you can verify that using the `status()` method. If you've lost your phone, then you need to remove and re-add the authenticator. Go to https://store.steampowered.com/twofactor/manage. The backup codes are one-use only.

If you want to use third-party authenticator together with steam app one, checkout https://github.com/ValvePython/steamctl

**Comment by 0xearl** [comment]
alright thank you for your response!. i'll close this now.
