### ISSUE TITLE
Query chat

### ISSUE THREAD

**Issue by OverLordGoldDragon** [ValvePython/steam#299]
I see it's a [work in progress](https://github.com/ValvePython/steam/issues/13); any working code that'd let me retrieve contents of a Friends chat window? Text and user names mainly.

**Comment by rossengeorgiev** [comment]
I have not look at exactly the flow of messages for the new chat system, but its all in the chat protobuf.

Retrieve message history: https://github.com/ValvePython/steam/blob/6f955c4b4d28dc800c38f10a33f9a18e09b83c51/protobufs/steammessages_chat.proto#L454-L482

Members and state: https://github.com/ValvePython/steam/blob/6f955c4b4d28dc800c38f10a33f9a18e09b83c51/protobufs/steammessages_chat.proto#L520-L526

These are unified messages, and you use https://steam.readthedocs.io/en/latest/api/steam.client.html#steam.client.SteamClient.send_um or `send_um_and_wait()`.

The RPC definitions are at the end of the file. So for example, https://github.com/ValvePython/steam/blob/6f955c4b4d28dc800c38f10a33f9a18e09b83c51/protobufs/steammessages_chat.proto#L1073-L1075

Your code might look like:

```python
client = SteamClient() 

#CChatRoom_GetChatRoomGroupState_Request
msg = client.send_um_and_wait("ChatRoom.GetChatRoomGroupState#1", {"chat_group_id": 12345"}) 

# CChatRoom_GetChatRoomGroupState_Response
print(msg) 
```

**Comment by OverLordGoldDragon** [comment]
Thanks; to refine my inquiry, I seek contents of a private chat window between myself and a Friend. This is more involved as I don't presume one can retrieve such information without authentication (... I hope?); is this something `steam` can handle? I looked around the API a bit; a closer pointer would help.

**Comment by rossengeorgiev** [comment]
You can get the recent messages of friends. It's a different service:

https://github.com/ValvePython/steam/blob/6f955c4b4d28dc800c38f10a33f9a18e09b83c51/protobufs/steammessages_friendmessages.proto#L6-L28

**Comment by OverLordGoldDragon** [comment]
Made several attempts, can't get `msg != None`; any suggestions? Also no error raised if I omit `steamid2`; not exactly sure how to handle these parameters.

```python
from steam.client import SteamClient
from steam.steamid import SteamID

#%%########################################
client = SteamClient()
client.cli_login()

id1_64 = 76561198066775726
id2_64 = #id64 of someone in Friends, with recent chat
id1 = SteamID(id1_64).id#as_32
id2 = SteamID(id1_64).id#as_32

#%%########################################
msg = client.send_um_and_wait(
    "FriendMessages.GetRecentMessages#1",
    {"steamid1": id1,
     "steamid2": id2,
     "count": 100,
     "most_recent_conversation": True},
)
print(msg)
```

**Comment by Gobot1234** [comment]
client.send_um_and_wait(
"FriendMessages.GetRecentMessages#1_Request", dict(steamid1=id1_64, steamid2=id2_64, count=100))
Should work.

**Comment by OverLordGoldDragon** [comment]
`ValueError: Failed to find method named: FriendMessages.GetRecentMessages#1_Request` unfortunately

**Comment by Gobot1234** [comment]
Oh sorry yes change that to just what you had for that so `FriendMessages.GetRecentMessages#1`

**Comment by rossengeorgiev** [comment]
Closing as it looks resolved

**Comment by OverLordGoldDragon** [comment]
My Dec 24 comment remains unresolved

**Comment by rossengeorgiev** [comment]
What's unresolved? In your code, `steamid1` and `steamid2` are the same, and then you are covering them to accountid and passing that. If look at the proto file, the type is `fixed64` and variables are name `steamid`. It's pretty clear that it's not expecting accountid. 

```python
id1 = SteamID(id1_64).id#as_32
id2 = SteamID(id1_64).id#as_32
```

`send_um_and_wait` will only return `None` on a timeout. That means either your login did not succeed, or you disconnected before the response, or the message you send is invalid in some way that causes Steam to disconnect you. I can't say which, since there is no debug log, indication what `EResult` was returned by `cli_login()`

Basic example, and it works as one would expect:

```python
>>> msg = client.send_um_and_wait("FriendMessages.GetRecentMessages#1", {
                'steamid1': client.steam_id, 'steamid2': 7xxxxxxxxxxxxxxxxxx, 'count': 2})
>>> print(msg)
<MsgProto(<EMsg.ServiceMethodResponse: 147> | CFriendMessages_GetRecentMessages_Response)>
-------------- header --
steamid: 7xxxxxxxxxxxxxxxxxx
client_sessionid: 111111111
jobid_target: 9
target_job_name: "FriendMessages.GetRecentMessages#1"
eresult: 1
---------------- body --
messages {
  accountid: 111111
  timestamp: 1234
  message: "asdasdasdasd"
}
messages {
  accountid: 222222
  timestamp: 1235
  message: "lol"
}
more_available: true
```
