### ISSUE TITLE
Implement mobile auth

### ISSUE THREAD

**Issue by philippj** [ValvePython/steam#30]
As the title says, it would be nice to have WebAuth with access to mobile pages, for trade confirmations etc.

A copy of WebAuth would be required with some uri and cookie changes.

I already worked on this and made a "fully working" prototype based on WebAuth. 

http://pastebin.com/2bRpaKu1

**Comment by rossengeorgiev** [comment]
This is just to get `oauth_token`? What it is used for?

**Comment by philippj** [comment]
In general it is used to retrieve all 'only-mobile' pages, that you can only access via the steam app.

Confirmations especially, but also the mobile polling system and simple ways to access steam account states.

A few changes have to be made to WebAuth, regarding mobile cookies and the `oauth` stuff.

`oauth_token` and `oauth_secure` replace the values for `steamLogin` and `steamLoginSecure`.

A additionall use for `oauth_token` is to refresh the active mobile session via `'https://api.steampowered.com/IMobileAuthService/GetWGToken/v0001', {'access_token': self.oauth['oauth_token']}`

Iam currently working on the mobile confirmations, so i can provide some example usage of MobileWebAuth

**Comment by rossengeorgiev** [comment]
Ok. That should be straightforward to implement. How often do you need to refresh the mobile session with `GetWGToken`? What does it return?

**Comment by philippj** [comment]
`GetWGToken` returns ' token' and `token_secure` to refresh the active session, so `steamLogin` and `steamLoginSecure` have to be replaced. `token` and `token_secure` are still `oauth` values, so keep that in mind.

One problem i encountered: you cant directly include mobile auth into web auth, because all codes generated with your steam secret are usable only one time. I have to look into it, maybe i will create some thread for authentication and take a more event style approach on tradeoffers and web stuff in general.

I will release my mobile and tradeoffer stuff when i finished it.

**Comment by rossengeorgiev** [comment]
Let me see if I understand this. The mobile auth, will give access all pages that web auth does plus mobile only pages. Correct? And at what point do I need to use `GetWGToken`? After some time? Immediately? On some interval?

**Comment by philippj** [comment]
> access all pages that web auth does 
many, but i havent spent much time testing that

> plus mobile only pages
yes

> And at what point do I need to use GetWGToken?
It is mainly used for refreshing the session when your it expires, `oauth_token` is valid as long you dont log off and can be used to access your old session, so you could save it and access the "same" session later.
