### ISSUE TITLE
bytes to text from multi

### ISSUE THREAD

**Issue by ValvojaX** [ValvePython/steam#301]
How do I convert the bytes I receive to string, for example from steam.enums.emsg.EMsg.Multi response?

**Comment by rossengeorgiev** [comment]
You don't have to. It is all done for you. `Multi` is just encapsulation when receiving multiple messages, and its handled automatically. Nearly all messages are protobufs, so finding the correct proto and using it to de-serialize the message body.

What are you trying to do exactly?

**Comment by ValvojaX** [comment]
Just want to see what I receive. How do I split the multiple messages from Multi object?

**Comment by rossengeorgiev** [comment]
Just configure `logging` and enable `SteamClient.verbose_debug`. That will log all the traffic.
