### ISSUE TITLE
MSRegion returns error using example code; "Expression cannot contain assignment" - Python 3.9.0

### ISSUE THREAD

**Issue by theunfrailhale** [ValvePython/steam#307]
Full Disclosure: Self taught casual.

I've been having good success with much of the library thus far, so my thanks for such a neat tool.

In trying to learn the query_master operation, as pasted from the code examples:

`steam.game_servers.query_master(filter_text='\\nappid\\500', max_servers=20, region=<MSRegion.World: 255>, master=('hl2master.steampowered.com', 27011), timeout=2)`

I'm getting no luck in leveraging the region argument, and persistently get this error in return:
```
steam.game_servers.query_master(filter_text='\\nappid\\500', max_servers=20, region=<MSRegion.World: 255>, master=('hl2master.steampowered.com', 27011), timeout=2)
                                                                                 ^
SyntaxError: expression cannot contain assignment, perhaps you meant "=="?     
```   

My intention is to set the region flag at US_East, but I've found no functional code examples including the base one.

Appreciate any help / insight.

**Comment by rossengeorgiev** [comment]
You are getting an error, because that invalid syntax. You can't copy the method signature like that as it displays values by their repr, which may or may not be valid syntax. Look at the examples: https://steam.readthedocs.io/en/latest/api/steam.game_servers.html#examples

```python
from steam import game_servers as gs

# these are defaults values for the parameters. You don't need to specify them unless you want to change them
gs.query_master(filter_text=r'\nappid\500', max_servers=20, region=gs.MSRegion.World, master=gs.MSServer.Source, timeout=2)

# for example, list 5 CSGO servers
for server_addr in gs.query_master(r'\appid\730', 5, region=gs.MSRegion.World):
    print(gs.a2s_info(server_addr))
