### ISSUE TITLE
add phone number

### ISSUE THREAD

**Issue by InstDev** [ValvePython/steam#312]
Can't add phone number:

`wa = MobileWebAuth('login')`
`wa.cli_login(password='password')`
`sa = SteamAuthenticator(backend=wa)`
`sa.add_phone_number('number')`

I recive email for add number, confirm email and i don't recive sms code and can't confirm it

**Comment by rossengeorgiev** [comment]
Looks like the process has changed, there is now always a email verification step. The another requests needs to be made to request sms code.

New flow:

1. Attempt to add new phone
2. **Verify email by clicking link in email**
3. **User confirms email verification. SMS code gets sent**
4. Get SMS code
5. Enter SMS code to finalize adding the phone

This change likely also applied for changing phone number

**Comment by InstDev** [comment]
Hello, i have a misunderstanding:
**3. User confirms email verification** - it's new method in module?
