### ISSUE TITLE
TOTP and SteamAuthenticator

### ISSUE THREAD

**Issue by rossengeorgiev** [ValvePython/steam#32]
Tasks:
- [x] steam totp code generation, confirmation key generation, time sync
- [x] process for adding/removing authenticator on an account
  - [x] Over WebAPI
    - [x] implement a way of obtaining mobile oauth token (#30)
  - [x] Over Unified Messages
- [ ] ~~consider implementing a standard way to encrypt and store authenticator secrets~~

**Comment by philippj** [comment]
TOTP login code, confirmation keys and steam server time https://github.com/philippj/steam-totp

**Comment by philippj** [comment]
> Process for adding/removing authenticator on an account '

Can be done both ways, webapi & unified messages.
Webapi seems cleaner tho.


For adding the mobile authenticator a valid phone number is required to recieve the sms, can be done via prepaid card, so its eventually free.
Full community access costs 5€

`POST`  `https://api.steampowered.com/ITwoFactorService/AddAuthenticator/v1/` with params: 
```
steamid: <steamid64>
access_token: <mobileOAuthToken>
authenticator_time: <unixTimestamp>
authenticator_type: <1=MobileAuthenticator>
device_identifier: <deviceID = SteamTOTP.generateDeviceID(steam64)>
sms_phone_id: 1
```
Returns:
```
status ( should be 1 )
+ shared_secret, revocation_code and so on, 
```
When status = 1 a sms is sent to the registered phone number and the verification can be finalized.

`POST` `https://api.steampowered.com/ITwoFactorService/FinalizeAddAuthenticator/v1/`
```
steamid: <steamid64>
access_token: <mobileOAuthToken>
authenticator_code: <totpCode>
authenticator_time: <unixTimestamp>
activation_code: <code recieved by sms>
```
Returns:
```
status: < should be 1 >
```

After this an email can be sent

`POST` `https://api.steampowered.com/ITwoFactorService/SendEmail/v1/`
```
steamid: <steamid64>
access_token: <mobileOAuthToken>
email_type: <2>
```
Returns:
`Unknown`

**Comment by philippj** [comment]
Details about `ITwoFactorService/AddAuthenticator`

A phone number has to be added first
Returns:
```
{
  "response": {
    "shared_secret"
    "serial_number"
    "revocation_code"
    "uri": "otpauth://totp/Steam:{USERNAME}?secret={SECRET (for generating login codes)}&issuer=Steam",
    "server_time"
    "account_name"
    "token_gid"
    "identity_secret"
    "secret_1"
    "status": 1
  }
}
```

`ITwoFactorService/FinalizeAddAuthenticator`
Returns:
```
{
    {
        "success": true,
        "want_more": false,
        "server_time": "1464771113", 
        "status": 2

    }
}
```
