### ISSUE TITLE
add phone number

### ISSUE THREAD

**Issue by InstDev** [ValvePython/steam#322]
Hi, all worked good but after update: `add_phone_number(phone_number)` return only bool (not dict) and i can't after confirm email continue

p.s. old version worked

**Comment by rossengeorgiev** [comment]
I can't understand what you are reporting. To add phone number follow the steps outlined here: https://steam.readthedocs.io/en/latest/api/steam.guard.html#steam.guard.SteamAuthenticator.add_phone_number

**Comment by InstDev** [comment]
`wa = MobileWebAuth('my_login')`
`wa.cli_login('my_password')`
`sa = SteamAuthenticator(backend=wa)`
`add_phone_number = sa.add_phone_number('my_phone_number')`
`print(add_phone_number) # return only True not dict`
`# there confirm link on my email`
`sa.confirm_email()` # and there error
![Безымянный](https://user-images.githubusercontent.com/33681835/113025258-6aea7300-9190-11eb-8562-b7cc93c4dfb1.png)

**Comment by InstDev** [comment]
Installed version from github (directly), now work fine

**Comment by rossengeorgiev** [comment]
Yes, you need to install from the repo to get the fix from #312, or wait for `v2.0` release.
