### ISSUE TITLE
Guard, mobile phone, send again sms

### ISSUE THREAD

**Issue by OliverTrust** [ValvePython/steam#323]
Sometimes, when add phone number to account, sms doesn't come at the first time. I suggest add method: send sms again

**Comment by rossengeorgiev** [comment]
What version are of `steam` package are you using?

If haven't installed from the master directly, then you are likely affected by #312 
Valve added email verification steps before sending SMS code, see https://steam.readthedocs.io/en/latest/api/steam.guard.html#steam.guard.SteamAuthenticator.add_phone_number
