### ISSUE TITLE
No module named 'gevent._gevent_c_hub_local'

### ISSUE THREAD

**Issue by EndSSgamesStudio** [ValvePython/steam#342]
I'm trying to get the username from steamClient.

I installed all requirements

but i got stuck in this

![image](https://user-images.githubusercontent.com/35436445/124140012-83ec1400-da5e-11eb-9639-34948db78c2e.png)

I'm following the user guide, which seems to use python 2
![image](https://user-images.githubusercontent.com/35436445/124140296-bc8bed80-da5e-11eb-9879-64343df4bc85.png)

it's been extremely complicated for me to use this library. Can someone help me? sorry to start an issue, i believe i am doing something wrong myself..
edit: python 3.7

**Comment by Qunik** [comment]
pip install -U steam[client]

**Comment by rossengeorgiev** [comment]
You are missing `gevent`. The install instruction specifically mention that you can use the `client` extra when installing to get `SteamClient` dependencies. `pip install -U steam[client]`
