### ISSUE TITLE
Can't import any discord modules at the same time.

### ISSUE THREAD

**Issue by LAD1** [ValvePython/steam#343]
If I import any discord modules such as, discord.py,dhooks, discord-components I get a massive error about "Monkey-patching ssl after ssl has already been imported may lead to errors", but whenever I remove the discord imports it goes away, no matter if I only put 1 discord import of any kind in I get the error, no other packages are interfering with this. Any possible fixes? It did work until my file randomly deleted itself which was sketchy, its not in my recycle bin either but ever since that incident discord and steam client dont like eachother.

**Comment by Qunik** [comment]
At the very beginning of your code write this:
```python
import gevent.monkey
gevent.monkey.patch_all()
```

**Comment by rossengeorgiev** [comment]
See #97
