### ISSUE TITLE
install steam[client] fails under zsh

### ISSUE THREAD

**Issue by EanNewton** [ValvePython/steam#347]
Running a pip install steam[client] or pipenv install steam[client] will return a no matches found if run from zsh; the same commands run successfully under bash.

See also: https://github.com/ValvePython/steam/issues/257

**Comment by rossengeorgiev** [comment]
You have to escape square brackets in zsh, as they have special meaning. Square brackets is how you install package extras, and there's nothing that can be done there.

**Comment by xPaw** [comment]
Perhaps add quotes? `pip install -U "steam[client]"`

It wasn't clear to me that brackets wasn't you showing optional thing.

**Comment by rossengeorgiev** [comment]
Good idea. I've updated the README
