### ISSUE TITLE
 I can not understand where to get the module with protobufs

### ISSUE THREAD

**Issue by Qunik** [ValvePython/steam#348]
On [this](https://steam.readthedocs.io/en/stable/api/steam.client.gc.html) documentation page
it says "The above code assumes that we have a myDotaModule that contains the appropriate protobufs needed to (de) serialize message for communication with GC."
But where can I get this module

**Comment by rossengeorgiev** [comment]
You create it.

Example implementation: https://github.com/ValvePython/dota2/blob/master/dota2/client.py  
In that case that module is `dota2.protobufs`.

https://github.com/ValvePython/dota2/blob/master/dota2/client.py#L17-L18
