### ISSUE TITLE
send message not work

### ISSUE THREAD

**Issue by UnderSpider** [ValvePython/steam#353]
```
from steam.client import SteamClient

client = SteamClient()
client.cli_login('username', 'password')
user = client.get_user(steam_id)
user.send_message('hello')
```
my account is logged in, but I didn't send any messages

**Comment by rossengeorgiev** [comment]
`.send_message()` only queues a message to be sent. Once you yield to the gevent event loop, it will get processed and sent. You can call `client.idle()`, or `.sleep(t)`, or any call that block for io to yield to the event loop.

**Comment by UnderSpider** [comment]
thanks, it worked!
