### ISSUE TITLE
What data is required for the get_encrypted_app_ticket function?

### ISSUE THREAD

**Issue by SeanPesce** [ValvePython/steam#354]
Is there documentation about the `userdata` parameter for the `get_encrypted_app_ticket` function, and how one might acquire or generate the data? The [documentation](https://steam.readthedocs.io/en/stable/api/steam.client.builtins.html#steam.client.builtins.apps.Apps.get_encrypted_app_ticket) I found for this function is incomplete.

**Comment by rossengeorgiev** [comment]
`userdata` as I understand it is just arbitrary data. The ticket is a wrapper around the data, that allows a backend system to authenticate the user sending it.

https://partner.steamgames.com/doc/api/ISteamUser#RequestEncryptedAppTicket
https://github.com/DoctorMcKay/node-steam-appticket

**Comment by SeanPesce** [comment]
Cool, thanks for the information!
