### ISSUE TITLE
Document './mysecrets.json'

### ISSUE THREAD

**Issue by luckydonald** [ValvePython/steam#363]
So the [docs](https://steam.readthedocs.io/en/latest/api/steam.guard.html) about steam authenticator/guard are about a `sa.secrets` or `mysecrets.json` file.
But it is missing a example of actual (fake) values.

**Comment by luckydonald** [comment]
Am trying to get the auth codes from my iPhone in there as I don't really wanna log out there, but have no clue what format it expects.

**Comment by Gobot1234** [comment]
It should be a dictionary with optionally shared_secret (for logging in) and identity_secret (less likely to be useful as it's for generating trading confirmation codes) keys which values should be base 64 strings.

**Comment by luckydonald** [comment]
So it needs the `shared_secret`? How does that look like?
I have 40 chars of 0-9, A-F as far as I can see.

**Comment by luckydonald** [comment]
Currently either it's a dead end or the format is wrong.
<img width="210" alt="image" src="https://user-images.githubusercontent.com/2737108/135589975-aeec47b9-c688-468b-8f93-9c0546c31935.png">

**Comment by rossengeorgiev** [comment]
Format is what Steam returns, you only need this:

```
{
    "account_name": "accountname",
    "shared_secret": "base64 secret",
    "status": 1,
    "token_gid": "token gid",
}
```
Or you can simply use `steamctl authenticator add --from-secret <BASE64 SHARED SECRET> <accountname>`

**Comment by luckydonald** [comment]
Closed? Is this documented in the docs now?

**Comment by r1bnc** [comment]
I dont think so? https://steam.readthedocs.io/en/stable/api/steam.guard.html

**Comment by luckydonald** [comment]
So it's still undocumented, I don't think that's good.
