### ISSUE TITLE
[FEATURE REQUEST] I have made the Chinese translation of the README, can you add it?

### ISSUE THREAD

**Issue by 2601677867** [ValvePython/steam#373]
[README.md](https://github.com/ValvePython/steam/files/7451640/README.md)

This project is very popular in China, and we thank the developers of this project for everything they have done.
So I made a README file with Chinese translation, please upload it if possible

**Comment by rossengeorgiev** [comment]
Thanks for the FR. However, I don't speak mandarin and there isn't anybody who can support translations as the project evolves.
