### ISSUE TITLE
Is there any way how to not input auth_code from guard each time?

### ISSUE THREAD

**Issue by kiddick** [ValvePython/steam#40]
node-dota2 (js analogue) stores `sentry` file with auth data so you just need to input login/password and steam guard code once.
Any possibilities to do this into that lib?

**Comment by philippj** [comment]
If you are talking about `twofactor_code`, you can look at my PR, there is it done the similar to node-dota2. (https://github.com/ValvePython/steam/pull/35)

**Comment by kiddick** [comment]
@philippj 
about this code
```
    else:
        code = raw_input("Enter Email Code: ")
        client.login(auth_code=code, **logOnDetails)

```

**Comment by kiddick** [comment]
Ahhh, looks like just enough to specify this param:

``` python

        Codes are required every time a user logins if sentry is not setup.
        See :meth:`set_credential_location`
```

**Comment by rossengeorgiev** [comment]
@kiddick You are probably looking for http://steam.readthedocs.io/en/stable/api/steam.client.html#steam.client.SteamClient.set_credential_location

**Comment by kiddick** [comment]
@rossengeorgiev lol just in time :) 
thanks

**Comment by kiddick** [comment]
Is it possible to reproduce "remember me" option to not log in each time at all?

**Comment by rossengeorgiev** [comment]
You need `login_key`, it's used together with the username to login. There are details in the latest docs. I've added some APIs to `v0.8.4` to hopefully simplify login code, which will be available today or tomorrow on pipy.
