### ISSUE TITLE
Show Shader Pre-Caching progress in the Downloads section.

### ISSUE THREAD

**Issue by LividJava** [ValvePython/steam#423]
**Is your feature request related to a problem? Please describe.**
While looking in my process manager i saw that fossilize_replay process was taking up an exorbitant amount of my CPU usage. After looking it up I saw that it was related to Shader Pre-Caching. It can be annoying at times to have my CPU bound suddenly from Caching and not knowing *why* its happening, especially when its happening in the middle of a stream (non-gaming), render, or other CPU intensive process.

**Describe the solution you'd like**
This feature is already partially implemented in a fashion, You can view the current progress of shader pre-caching, though it's hidden from the user. Having this in downloads, and being able to view its progress and potentially any other games that need to be pre-cached while allowing us to pause the process temporarily would be beneficial for someone who might stream or need to render.

![image](https://user-images.githubusercontent.com/7604544/211435073-19923462-417c-4c33-a62c-fd142444d20b.png)

**Describe alternatives you've considered**
If not Downloads, then having the game entry itself show the pre-cache progress.

**Comment by Gobot1234** [comment]
This isn't a repository for issues with the steam client, if you want to throw your issue into the right direction try https://github.com/ValveSoftware/steam-for-linux/issues

**Comment by LividJava** [comment]
Closing as this isn't the right place then.
