### ISSUE TITLE
Writing, loading and sending sentry files not working

### ISSUE THREAD

**Issue by nukeop** [ValvePython/steam#43]
Hi

Looks like the client won't write and/or load and send sentry files automatically.

_handle_update_machine_auth is bound to be called on EMsg.ClientUpdateMachineAuth event but it looks like it's never triggered.

Is it not implemented yet or expected to work?

**Comment by rossengeorgiev** [comment]
By default the sentry file is not persisted to disk, you will have to explicitly setup a credential location. Then a sentry file will be saved per account after a successful login and used for subsequent logins.

http://steam.readthedocs.io/en/stable/api/steam.client.html#steam.client.SteamClient.set_credential_location

**Comment by nukeop** [comment]
I'm doing this:

    client.set_credential_location('sentryfiles')

where client is a SteamClient object.

Sudo doesn't change anything but it shouldn't need it anyway. I tried a couple of different locations including an empty string and '.'. Looking at the code there should be no reason for it not to work.

**Comment by rossengeorgiev** [comment]
Are you setting the location before attempting to login?

**Comment by nukeop** [comment]
Yes.

I'm doing something like this:

    def __init__(self):
        User.verbose_debug = True
        User.client.set_credential_location('')
        if User.client.relogin_available:
            User.client.relogin()
        else:
            User.client.login(config.user, config.pwd)

2fa codes and so on are handled in a separate function but it's not relevant here.

I tried debugging with pdb and it does not enter _handle_update_machine_auth in SteamClient class after a successful login.

**Comment by rossengeorgiev** [comment]
I'm not sure how well pdb plays with gevent. If you setup logging on debug level there should be a line with `EMsg.ClientUpdateMachineAuth` event. I haven't encountered a case where there isn't. Another thing you can check is for `cm_servers.json` file in the credential location. If that's missing then I would check whether the path is valid and writable. `''` is not a valid location, although the sentry location code appears to check incorrectly. Shouldn't affect the issue here, but `cm_servers.json` won't be created if that's the path.

**Comment by nukeop** [comment]
Ok, two things:

1. You can't use ~ as a shorthand for home directory, python doesn't like it - I can save a (meaningless) sentry file manually by setting credential location to `/home/username/something` and calling `store_sentry` manually

2. Setting logging to debug shows that event `EMsg.ClientUpdateMachineAuth` is called only sometimes after logging in. Even when it's triggered it does not create a sentry file. `cm_servers.json` never appears.

I tried following the same procedure as this gist: https://gist.github.com/devsaider/90726d45d815fb7919ba9c3e22963b61

But still no luck.

**Comment by nukeop** [comment]
After some more debugging, I solved it with both sentry file and `cm_servers.json` being created. The key is to let the program sleep for a couple of seconds so that it can receive and handle all events before quitting. Thanks for the help.

**Comment by rossengeorgiev** [comment]
Oh ok. I was just taking a look at the code you linked, but it seemed completely normal. I don't think I can `^C` it fast enough before the files are created. I'm guessing maybe you were running something different. I should've just asked for code and debug log earlier. Would've been easier to figure out.
