### ISSUE TITLE
EMsg.ClientFriendsList event not calling registered callbacks in SteamClient

### ISSUE THREAD

**Issue by nukeop** [ValvePython/steam#44]
Hi

I started porting a little steam chatbot from C# SteamKit to python recently.

I'm trying to get a list of friends after logging in - according to logs SteamClient instance receives the relevant event:

```
Incoming: <MsgProto <EMsg.ClientFriendsList: 767>>
Emit event: <EMsg.ClientFriendsList: 767>
```

But it doesn't trigger the callback, which I'm registering like this:

```
def __init__(self):
    self.client.on(EMsg.ClientFriendsList, self.on_client_friends_list)

def on_client_friends_list(self, msg):
        logger.info("Received ClientFriendsList")
        logger.info(msg)
```

There is more code but that's the gist of it - the bottom line is that if I do the same with, say EMsg.ClientAccountInfo, it calls the registered callback. 

Any advice?

**Comment by rossengeorgiev** [comment]
It will certainly get called. It doesn't happen immediately after the debug line.  Can't really comment further with seeing the whole code.

**Comment by nukeop** [comment]
Here's a minimal example:
https://gist.github.com/nukeop/5dc4a1e7832928b718b8a376a406975b

Although by now I did some more debugging and it turns out my understanding was wrong - some events need to be explicitly received by using, for example `client.wait_event(EMsg.ClientAccountInfo)`. I was confused because some events (not those named with EMsg values but with strings, such as `'auth_code_required'`), will be triggered automatically. I'll leave the code above and the explanation for posterity, in case anyone makes the same mistake in the future.

**Comment by rossengeorgiev** [comment]
`wait_event` is just a different way to receive an event. It allows your code to yield to event loop and let other greenlets to run. Until the event happens or it timeouts, then the code is resumed.

Every function you register is not called directly. Instead a greenlet is scheduled to run it. You will need to yield excplicitly to let other stuff run.

**Comment by rossengeorgiev** [comment]
`wait_event` is just a different way to receive an event. It allows your code to yield to event loop and let other greenlets to run. Until the event happens or it timeouts, then the code is resumed.

Every function you register is not called directly. Instead a greenlet is scheduled to run it. You will need to yield excplicitly to let other stuff run.

The code you linked uses `time.sleep`, which won't yield, so your program enda and nothing happens. Istead use `gevent.sleep`.

**Comment by nukeop** [comment]
Nice, thanks a lot for clarification.

BTW. As I port my bot I might be able to figure out some useful usage patterns. Would it be helpful if I made some contributions to the documentation?

**Comment by rossengeorgiev** [comment]
Absolutely. I will be adding some sample programs soon.
