### ISSUE TITLE
No Libc.so.6 in ubuntu 32 [BUG]

### ISSUE THREAD

**Issue by webmaster-exit-1** [ValvePython/steam#447]
![image](https://github.com/ValvePython/steam/assets/98633966/794fa19f-88d3-435d-8d46-034e5f2ddfd2)
I have everything installed this lib is missing in the launcher in ubuntu 32 folder

**Comment by webmaster-exit-1** [comment]
fix it valve. I asked multiple times to know which file or line of code i need to remove so i can play the games i paid for without using steam, but i keep getting denied this. Fix your launcher.

**Comment by webmaster-exit-1** [comment]
![image](https://github.com/ValvePython/steam/assets/98633966/a9085606-c153-4ef2-b327-a458c38e3317)

**Comment by Gobot1234** [comment]
This isn't the place to report bugs in steam's client. This project isn't affiliated with Valve in any way
