### ISSUE TITLE
Cli example

### ISSUE THREAD

**Issue by b3mb4m** [ValvePython/steam#45]
http://steam.readthedocs.io/en/stable/user_guide.html#cli-example

`Traceback (most recent call last):`
`  File "test3.py", line 14, in <module>`
`    client = SteamClient()`
`  File "/usr/local/lib/python2.7/dist-packages/steam/__init__.py", line 16, in __new__`
`    from steam.client import SteamClient as SC`
`  File "/usr/local/lib/python2.7/dist-packages/steam/client/__init__.py", line 22, in <module>`
`    from eventemitter import EventEmitter`
`  File "/usr/local/lib/python2.7/dist-packages/eventemitter/__init__.py", line 3, in <module>`
`    from .emitter import EventEmitter`
`  File "/usr/local/lib/python2.7/dist-packages/eventemitter/emitter.py", line 11`
`    async def _try_catch_coro(emitter, event, listener, coro):`
`            ^`
`SyntaxError: invalid syntax`
`

System : Linux b 4.0.0-kali1-686-pae #1 SMP Debian 4.0.4-1+kali2 (2015-06-03) i686 GNU/Linux
Python : 2.x

**Comment by rossengeorgiev** [comment]
I suspect this is due to an existing package on your system colliding with
one of the dependences.

**Comment by b3mb4m** [comment]
I'm really not sure that throw million error.

http://pastebin.ubuntu.com/23102265/


Which system do you recommend to run it smootly?

**Comment by b3mb4m** [comment]
Just fixed on both py2 & py3-Doing everything manually-

Also in codes has some errors
          Traceback (most recent call last):
               File "test3.py", line 34, in <module>
               print ("SteamID: %s" % repr(client.steamid))
          AttributeError: 'SteamClient' object has no attribute 'steamid'

i just delete it and its working now.Hope you can fix these errors soon ~~

**Comment by rossengeorgiev** [comment]
It seems the example is outdated. It best to use virtualenv so you don't
break you system packages.

**Comment by b3mb4m** [comment]
Just pm you via email can you check it ? Or pm me i need some help about unmentioned functions.

b3mb4m@tuta.io
