### ISSUE TITLE
How we can send message & delete friend friends ? 

### ISSUE THREAD

**Issue by b3mb4m** [ValvePython/steam#46]
message = MsgProto(EMsg.ClientAddFriend)
    message.body.steamid_to_add = userid
    resp = client.send_message_and_wait(message, EMsg.ClientAddFriendResponse)

This is enought to send friend requests but i cant find any document how to send message from my friendlist & delete friends my list.I did read almost all documentation, did i miss something ? Some help would be great.

**Comment by rossengeorgiev** [comment]
There is an API for that. It looks like the docs weren't updated after some code changes.

**Comment by rossengeorgiev** [comment]
Here is the `friends` API: http://steam.readthedocs.io/en/latest/api/steam.client.builtins.html#module-steam.client.builtins.friends

**Comment by b3mb4m** [comment]
Seems like not working, 

            users = SteamFriendlist(client)

return 0 always.

**Comment by rossengeorgiev** [comment]
An instance of SteamFriendlist is accessible via `client.friends`.

**Comment by b3mb4m** [comment]
I already try it that's why i said.Still same result

            <SteamFriendlist 0 users>

**Comment by b3mb4m** [comment]
Also just try now,

         print client.friends.remove(userid)
         print client.friends.add(userid)  //Not working

Remove function working but add is not.Not test send message function yet.

**Comment by rossengeorgiev** [comment]
The code above certainly works, if you yield to the event loop. If the application exits, it won't work, since the message never get send. You can yield with either `gevent.sleep()`, `gevent.idle()`, `client.run_forever()`, `wait_event`, etc.
