### ISSUE TITLE
[LEGAL] Dependency gevent-eventemitter is unlicensed

### ISSUE THREAD

**Issue by Pandapip1** [ValvePython/steam#471]
`gevent-eventemitter` has no license (see https://github.com/rossengeorgiev/gevent-eventemitter/issues/5). You should find a suitable replacement.

**Comment by Gobot1234** [comment]
It's already under MIT according to the setup.py https://github.com/rossengeorgiev/gevent-eventemitter/blob/486564ca5b0b0934d5a585cfafdc73845f3ba312/setup.py#L21. The author of this library is also the author of this so they're unlikely to find a replacement

**Comment by Pandapip1** [comment]
Didn't see that in the `setup.py`. Closing.
