### ISSUE TITLE
Is there EMsg Handler to use when someone add bot to the friendlist?

### ISSUE THREAD

**Issue by alexche8** [ValvePython/steam#48]
Also, if you have some time, provide an example please.

**Comment by alexche8** [comment]
Any comment maybe?

**Comment by rossengeorgiev** [comment]
My bad, I closed the question by mistake while reading on my phone. Yes, there are plans to provide more complete examples or recipes if you will. As to when it would happen, well, not sure. I'm getting sidetracked by other things at moment, but it certainly happen in the near future.

**Comment by nukeop** [comment]
Do something like this, assuming `client` is an instance of `steam.client.SteamClient`:
```

client.on(EMsg.ClientAddFriendResponse, on_friend_added)

def on_friend_added(msg):
        if msg.body.eresult != 1:
            print "Error adding friend {}".format(msg.body.persona_name_added)
        else:
            print "{} ({})is now a friend".format(msg.body.persona_name_added, msg.body.steam_id_added)
```

**Comment by rossengeorgiev** [comment]
You have to listen for `EMsg.ClientFriendsList` and then resolve which `steamids` are invites by checking relationship status. This is already implemented as `SteamFriendlist`.

http://steam.readthedocs.io/en/stable/api/steam.client.builtins.html#module-steam.client.builtins.friends
