### ISSUE TITLE
SteamUser times out when querying Steam servers for certain attributes

### ISSUE THREAD

**Issue by nukeop** [ValvePython/steam#52]
I will debug some more and post more details later.

Not sure if this is an issue with Steam servers or the library, and I'm not sure what causes that or how to reproduce it.

**Comment by rossengeorgiev** [comment]
I will need to see some code. `SteamUser` instances are weakly cached, meaning that if you don't keep the reference it will be destroyed. Then the next time you call `get_user` you will get a new instance, which involves some back and forth with steam.

**Comment by nukeop** [comment]
Some more info.

If a user is not on the friend list, get_user attempts to create a new SteamUser instance and add it to the cache, using supplied steam id. This creates a valid SteamUser, but trying to get data from it (like name, last logoff, etc) will require querying Steam servers.

Now I'm trying to get the name from this instance. In most cases, this causes a long delay and returns None. Something with SteamUser.get_ps is wrong when calling it with 'player_name', possibly also with other valid parameters. I think it's hitting a timeout (which is 30 by default) when querying servers?

**Comment by rossengeorgiev** [comment]
I've made `SteamUser `request state when it is missing. It is expected that callers of `get_user` will maintain a reference of the instance, otherwise the instance will be destroyed. `SteamFriendlist` for example will keep reference of the `SteamUser` instances, so they will keep on living. I am guessing, but if you are doing something related to steam groups, you will need to keep list of members as a list of `SteamUser` instances.

**Comment by nukeop** [comment]
Here's what I'm doing in more detail and with code.

I have a `SteamClient `instance that I keep in my "`User`" class. This class is also set to join any group chat my bot is invited to. Now I'm trying to use the new event (`ClientChatEnter`) that's emitted when the client joins a group chat, which has in its body, among other things, the list of steam IDs of people already in it. My class also keeps a dictionary of the group chats: keys are group ids, values are lists of steam IDs. When the client joins the chat, I'm trying to populate the corresponding list, and print the usernames. A minimal example looks like this:

```
self.client.on(EMsg.ClientChatEnter, self.on_chat_enter)

def on_chat_enter(self, msg):
    for member in msg.body.memberList:
        self.chats[msg.body.steamIdChat].append(member['steamid'])
        suser = self.client.get_user(member['steamid'], False)
        print suser.name
```

Trying to print `suser.name` times out for users that aren't on my bot's friend lists and returns None instead of the name. I could store `SteamUser` instances instead of just IDs but why is it failing to fetch the name here? The reference to `SteamUser `is still alive when I'm trying to print.

**Comment by nukeop** [comment]
Okay, now I see my error - `fetch_persona_state ` not only causes it to fetch the online/away/offline status, but also the name itself. Thanks for the change.

**Comment by rossengeorgiev** [comment]
I suspected that too be the error. You've probably copied the code from SteamFriendlist, it does this as an optimization. It batches all persona checks into one request rather than a request per user.
