### ISSUE TITLE
Implement CDN Client

### ISSUE THREAD

**Issue by rossengeorgiev** [ValvePython/steam#54]
This means authentication and access to the CDN network to make possible the download of app content

- [x] authentication
- [x] manifest download and decryption
- [x] download of chunks and decryption

Things needed in `SteamClient`

- [x] fetching app, package and depot info
- [x] getting a list of content servers

**Comment by nukeop** [comment]
This can be useful:
https://bitbucket.org/AzuiSleet/pysteamkit/src/0fdcb692aa606890e23a8bbba3abd2bb90f05d84/pysteamkit/steam3/cdn_client.py

This is an earlier, by now mostly abandoned, attempt to port SteamKit to Python, but the parts that  implement CDN client functionality are working. MIT license, so the code can be reused freely.

**Comment by rossengeorgiev** [comment]
Yep. I am aware of the project. I've been meaning to port it just haven't found the time.

**Comment by judge2020** [comment]
Any update?
