### ISSUE TITLE
'!!! NO BODY !!!' for some MsgProto() objects

### ISSUE THREAD

**Issue by molesteev** [ValvePython/steam#57]
Hello. 
When I trying to make objects, like 
`MsgProto(EMsg.ClientCreateAccountProto) or MsgProto(EMsg.ClientCreateAccountProtoResponse),`
body of these objects has only '!!! NO BODY !!!'.
So I have to write some weird things:
`a.body = steammessages_clientserver_2_pb2.CMsgClientCreateAccount()`
But I can't get response because it's have '!!! NO BODY !!!', too.
get_cmsg() with some EMsg's return None.
Is it my mistake or something else?
And what does '!!! NO BODY !!!' means?

**Comment by rossengeorgiev** [comment]
There is a function takes a `EMsg` and attempts to located the corresponding protobuf message. You get that body when it fails.

There is a `dict` containing the mappings in `steam.core.msg`: https://github.com/ValvePython/steam/blob/f0e337fcde26a2c13d8785d9851cf750ff7e9c3c/steam/core/msg/__init__.py#L14-L23

If you know the mapping you could tell me, or submit a PR.

As a workaround you could add them at runtime during initialization steps:

```python
from steam.core.msg import cmsg_lookup_predefined
from steam.protobufs import steammessages_clientserver_2_pb2

cmsg_lookup_predefined.update({
    EMsg.ClientCreateAccountProto: steammessages_clientserver_2_pb2.CMsgClientCreateAccount,
    EMsg.ClientCreateAccountProtoResponse: steammessages_clientserver_2_pb2.CMsgClientCreateAccountResponse,
    })
