### ISSUE TITLE
Implement adding phone number in SteamAuthenticator

### ISSUE THREAD

**Issue by molesteev** [ValvePython/steam#59]
It would be nice to add phone number using SteamAuthenticator, but it needs sessionid. 
We can get sessionid in something like that
```python
def get_sessionid(mobile_session):
    headers = {
        'X-Requested-With' : 'com.valvesoftware.android.steam.community',
        'referer' : 'https://steamcommunity.com/mobilelogin?oauth_client_id=DE45CD61&\
            oauth_scope=read_profile%20write_profile%20read_client%20write_client'
    }
    mobile_session.session.get('https://steamcommunity.com/login?oauth_client_id=DE45CD61&\
                oauth_scope=read_profile%20write_profile%20read_client%20write_client',
                headers=headers, timeout=15)
    sessionid = mobile_session.session.cookies['sessionid']
    return sessionid
```
where 'session' is WebAuth object
and add phone number in that way (it may be better, but I'm not good in coding):
```python
class PhoneLinker:
    def __init__(self, medium=None):
        self.phone_number = None
        self.sessionid = medium.session.cookies['sessionid'] \
                if 'sessionid' in medium.session.cookies \
                else get_sessionid(medium)
        self._ajaxurl = 'https://steamcommunity.com/steamguard/phoneajax'
        if isinstance(medium, MobileWebAuth):
            if not medium.complete:
                raise SteamAuthenticatorError("MobileWebAuth instance not logged in")
            self.medium = medium
                        
    def _has_phone_attached(self):
        if not self.medium:
            return None
        post_data = {
            'op' : 'has_phone',
            'arg' : 'null',
            'sessionid' : self.medium.session.cookies['sessionid']
        }
        resp = self.medium.session.post(self._ajaxurl, post_data, timeout=15)
        return resp.json()['has_phone']
        
    def add_phone_number(self, phone_number=None):
        if not self.phone_number and phone_number:
            phone_number = phone_number.replace('-','').replace('(','').replace(')','')
            if not phone_number or len(phone_number) < 10:
                return False
            if phone_number[0] != '+':
                return False
            self.phone_number = phone_number
        elif not self.phone_number and not phone_number:
            return False
        post_data = {
            'op' : 'add_phone_number',
            'arg' : self.phone_number,
            'sessionid' : self.medium.session.cookies['sessionid']
            }
        resp = self.medium.session.post(self._ajaxurl, post_data, timeout=15)
        if not resp:
            return False
        return resp.json()['success']
```
Can this be added in SteamAuthenticator class?

**Comment by molesteev** [comment]
#60

**Comment by rossengeorgiev** [comment]
Sounds like a good idea to me. I'm not sure about the code. Does the `sessionid` from `MobileWebAuth` not work for adding the number?

**Comment by molesteev** [comment]
You mean `sessionid` from `SteamClient`? If it is, answer is no, because there `sessionid` is number with small lenght, but `WebAuth` needs `sessionid` that looks like small hash maybe: `df5567a786746239587c5d75`

**Comment by rossengeorgiev** [comment]
The `sessionid` from `MobileWebAuth`. Have tried using it for the phone operations? Also, are there any other operations other than `has_phone` and `add_phone_number`?

**Comment by molesteev** [comment]
Sorry, but I can't find any `sessionid` in `MobileWebAuth`. 
I remember it is somewhere, but can't find now. When I tried to use it for phone operations, it didn't work. Response said `sessionid is wrong` or something like this. 
I believe it is possible to make something similar to [https://github.com/geel9/SteamAuth/blob/master/SteamAuth/AuthenticatorLinker.cs](url)
There are also `_checkSMSCode` operation.
But if you add this code without changing `finalize` function, it wouldn't work and I don't why. I tried to add `add_phone_number` function, but then `finalize` function always return `EResult.TwoFactorActivationCodeMismatch`

**Comment by rossengeorgiev** [comment]
Right. `sessionid` is just a cookie, and it can be anything pretty much. Looks like the default cookies won't have it initially. Usually, once you make a request and don't have `sessionid` cookie, you get one generated.

Anyway, this is a good suggestion and it should be a part of `SteamAuthenticator`. I'll look into it.

**Comment by molesteev** [comment]
Ok, Thanks

**Comment by molesteev** [comment]
Version in first comment always return "Wrong sms code", here's right request for adding phone to account
```python
get('https://store.steampowered.com/phone/add_ajaxop',
    params = {
        "op": "get_phone_number",
        "input": phone_number,
        "sessionID": get_sessionid(session),
        "confirmed": 0,
        "checkfortos": 1
    })
```
and after we can use SteamAuthenticator to add and finalize twofactor.

**Comment by molesteev** [comment]
Version in first comment doesn't work, finalize function returns "Wrong sms code", here's right request to add phone to account
```python
get('https://store.steampowered.com/phone/add_ajaxop',
    params = {
        "op": "get_phone_number",
        "input": phone_number,
        "sessionID": sessionid,
        "confirmed": 0,
        "checkfortos": 1
    })
```
