### ISSUE TITLE
Sentry files doesn't work

### ISSUE THREAD

**Issue by lopezloo** [ValvePython/steam#64]
Steam is asking me for 2FA code even if I pass sentry file (which got generated on previous logon).

Could it be because `machine_id` is missing? [SteamKit2/SteamKit2/Steam/Handlers/SteamUser/SteamUser.cs#L343](https://github.com/SteamRE/SteamKit/blob/d9a1da3513e2747dbe2c3d752aebf7464e2d900b/SteamKit2/SteamKit2/Steam/Handlers/SteamUser/SteamUser.cs#L343)

**Comment by rossengeorgiev** [comment]
No. It always requires 2FA code. There are 2 ways around that, either you use `SteamAuthenticator` to generate a code for your call to `login` (user, pass, 2fa code), or persist your `login_key` (user, loginkey). Keep in mind that if your login key gets regenerated while you are offline, it won't let you login.

If you are just looking to reconnect on a `SteamClient` instance that was logged on once already then you can use http://steam.readthedocs.io/en/latest/api/steam.client.html#steam.client.SteamClient.relogin
