### ISSUE TITLE
[Help]Can someone explain the two args for steam.client.user

### ISSUE THREAD

**Issue by jensenhuangyankai** [ValvePython/steam#65]
http://steam.readthedocs.io/en/latest/api/steam.client.user.html 
What is the SteamID format and what is meant by steam as the second arg

**Comment by rossengeorgiev** [comment]
A instance of`SteamClient`, but you shouldn't be using that directly. You can get a `SteamUser` instance via http://steam.readthedocs.io/en/latest/api/steam.client.builtins.html#steam.client.builtins.user.User.get_user

**Comment by jensenhuangyankai** [comment]
Rossen, could you also explain how does chat work? How can I check for incoming chat and reply too?
Thanks

**Comment by rossengeorgiev** [comment]
Here is an example of simply echoing every received message

```python
@client.on(client.EVENT_CHAT_MESSAGE)
def handle_chat_message(user, text):
    user.send_message("You said: " + text)
```
