### ISSUE TITLE
change_status not working?

### ISSUE THREAD

**Issue by Snaacky** [ValvePython/steam#67]
Perhaps this is an improper usage of change_status but I have taken one the basic login examples and after the 4 `print` lines thrown in:

`client.change_status(player_name="new_username")`

However nothing changes, nothing errors, and the application exits on the example `client.logout()` as if everything worked fine. Am I misusing this function or am I missing something here?

**Comment by lopezloo** [comment]
I think you need to add `persona_state`.

**Comment by Snaacky** [comment]
Added `from steam.enums import EPersonaState` into imports and changed the previous line to:

`client.change_status(persona_state=EPersonaState.Online, player_name="new_username")` 

Still nothing.

**Comment by Snaacky** [comment]
EDIT: Didn't realize I wasn't in a persistent instance. Using persistent instance and it works perfectly.

**Comment by rossengeorgiev** [comment]
Keep in mind that when you call those functions a message is sent to the steam network, and the round trip takes time. You have to wait explicitly until a response. A response is also not guaranteed.
