### ISSUE TITLE
AttributeError: 'SteamClient' object has no attribute '_listeners'

### ISSUE THREAD

**Issue by Zwork101** [ValvePython/steam#70]
After trying to connect to steam, It left me with this error:
`Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    client = SteamClient()
  File "C:\Users\Zwork101\AppData\Local\Programs\Python\Python36-32\lib\site-packages\steam\__init__.py", line 26, in __new__
    return SC(*args, **kwargs)
  File "C:\Users\Zwork101\AppData\Local\Programs\Python\Python36-32\lib\site-packages\steam\client\__init__.py", line 58, in __init__
    CMClient.__init__(self)
  File "C:\Users\Zwork101\AppData\Local\Programs\Python\Python36-32\lib\site-packages\steam\core\cm.py", line 88, in __init__
    self.on(EMsg.ChannelEncryptRequest, self.__handle_encrypt_request),
  File "C:\Users\Zwork101\AppData\Local\Programs\Python\Python36-32\lib\site-packages\eventemitter\emitter.py", line 81, in add_listener
    self.emit('new_listener', event, listener)
  File "C:\Users\Zwork101\AppData\Local\Programs\Python\Python36-32\lib\site-packages\steam\core\cm.py", line 96, in emit
    super(CMClient, self).emit(event, *args)
  File "C:\Users\Zwork101\AppData\Local\Programs\Python\Python36-32\lib\site-packages\eventemitter\emitter.py", line 262, in emit
    listeners = self._listeners[event]
AttributeError: 'SteamClient' object has no attribute '_listeners'`

After trying to assign `SteamClient()` to `client`

`from steam import SteamClient`
`client = SteamClient()`

After finding the file that contains the error, I could not find a solution. Help?

**Comment by rossengeorgiev** [comment]
Looks like its trying to use incorrect package. Did you install with `pip install steam[client]` ?

**Comment by Zwork101** [comment]
I did `pip install steam` without the client at the end, so Ill try that, and if that doesn't work, Ill do the `virtualenv`

**Comment by Zwork101** [comment]
OK, thanks for responding quickly. I was able to assign the variable.

**Comment by rossengeorgiev** [comment]
`client` extra installs the additional dependencies for SteamClient

**Comment by rafalolszewski94** [comment]
Seems like you can't install deps via `pip install steam[client]` did something change? Or I am doing something wrong?

**Comment by bytechef** [comment]
I am also having this error:
```Python
$ pip install -U steam      
Defaulting to user installation because normal site-packages is not writeable
Requirement already up-to-date: steam in /home/cook/.local/lib/python3.8/site-packages (1.0.2)
Requirement already satisfied, skipping upgrade: six>=1.10 in /usr/lib/python3.8/site-packages (from steam) (1.15.0)
Requirement already satisfied, skipping upgrade: pycryptodomex>=3.7.0 in /home/cook/.local/lib/python3.8/site-packages (from steam) (3.9.8)
Requirement already satisfied, skipping upgrade: requests>=2.9.1 in /usr/lib/python3.8/site-packages (from steam) (2.24.0)
Requirement already satisfied, skipping upgrade: vdf>=3.3 in /home/cook/.local/lib/python3.8/site-packages (from steam) (3.3)
Requirement already satisfied, skipping upgrade: cachetools>=3.0.0 in /home/cook/.local/lib/python3.8/site-packages (from steam) (4.1.1)
Requirement already satisfied, skipping upgrade: chardet>=3.0.2 in /usr/lib/python3.8/site-packages (from requests>=2.9.1->steam) (3.0.4)
Requirement already satisfied, skipping upgrade: idna>=2.5 in /usr/lib/python3.8/site-packages (from requests>=2.9.1->steam) (2.10)
Requirement already satisfied, skipping upgrade: urllib3>=1.21.1 in /usr/lib/python3.8/site-packages (from requests>=2.9.1->steam) (1.25.10)
$ pip install -U steamclient
Defaulting to user installation because normal site-packages is not writeable
Requirement already up-to-date: steamclient in /home/cook/.local/lib/python3.8/site-packages (1.2)
Requirement already satisfied, skipping upgrade: requests in /usr/lib/python3.8/site-packages (from steamclient) (2.24.0)
Requirement already satisfied, skipping upgrade: chardet>=3.0.2 in /usr/lib/python3.8/site-packages (from requests->steamclient) (3.0.4)
Requirement already satisfied, skipping upgrade: idna>=2.5 in /usr/lib/python3.8/site-packages (from requests->steamclient) (2.10)
Requirement already satisfied, skipping upgrade: urllib3>=1.21.1 in /usr/lib/python3.8/site-packages (from requests->steamclient) (1.25.10)
$ python test.py
/home/cook/.local/lib/python3.8/site-packages/gevent/monkey.py:1021: MonkeyPatchWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. It may also silently lead to incorrect behaviour on Python 3.7. Please monkey-patch earlier. See https://github.com/gevent/gevent/issues/1016. Modules that had direct imports (NOT patched): ['urllib3.util.ssl_ (/usr/lib/python3.8/site-packages/urllib3/util/ssl_.py)', 'urllib3.util (/usr/lib/python3.8/site-packages/urllib3/util/__init__.py)']. 
  _queue_warning(
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    client = SteamClient()
  File "/home/cook/.local/lib/python3.8/site-packages/steam/client/__init__.py", line 63, in __init__
    CMClient.__init__(self)
  File "/home/cook/.local/lib/python3.8/site-packages/steam/core/cm.py", line 91, in __init__
    self.on(EMsg.ChannelEncryptRequest, self.__handle_encrypt_request),
  File "/home/cook/.local/lib/python3.8/site-packages/eventemitter/emitter.py", line 81, in add_listener
    self.emit('new_listener', event, listener)
  File "/home/cook/.local/lib/python3.8/site-packages/steam/core/cm.py", line 99, in emit
    super(CMClient, self).emit(event, *args)
  File "/home/cook/.local/lib/python3.8/site-packages/eventemitter/emitter.py", line 262, in emit
    listeners = self._listeners[event]
AttributeError: 'SteamClient' object has no attribute '_listeners'
```

**Comment by rossengeorgiev** [comment]
@bytechef you've installed the wrong package. https://pypi.org/project/steamclient/ is not this. You want `pip install -U steam[client]`. Notice the square brackets.

https://github.com/ValvePython/steam#install

**Comment by bytechef** [comment]
Thank you so much! I think zsh was messing me up cause I tried that and it broke:
```bash
$ pip install -U steam[client]
zsh: no matches found: steam[client]
```
so I assumed it was just steamclient, but it works if I add quotes:
```bash
$ pip install -U "steam[client]"
```

**Comment by rossengeorgiev** [comment]
yes, in zsh square brackets have special meaning, so you have to add quotes or escape them
