### ISSUE TITLE
Error: EResult.Fail, unable to send friend requests

### ISSUE THREAD

**Issue by Zwork101** [ValvePython/steam#71]
After logging in, (I checked, the account went online), I implemented the same code (revised for python 3) from that doc of this modual. Every time I went online and it tryed to send the request it ended up in a 
`Error: EResult.Fail`
I have tried different ID's for the same account, mainly using the ID from SteamID. I have been unsuccessful through different revisions, and need help.
Here's the code:

`from steam import SteamClient`
`from steam.enums import EResult`
`from steam.enums.emsg import EMsg`
`from steam.core.msg import MsgProto`

`client = SteamClient()`
`client.cli_login()`

`message = MsgProto(EMsg.ClientAddFriend)`
`message.body.steamid_to_add = 325018245`

`resp = client.send_message_and_wait(message, EMsg.ClientAddFriendResponse)`

`if resp.eresult == EResult.OK:`
   ` print("Send a friend request to %s (%d)" % (repr(body.persona_name_added), body.steam_id_added))`
`else:`
    `print("Error: %s" % EResult(resp.eresult))`
`

**Comment by rossengeorgiev** [comment]
It requires a `SteamID`, the numbers that starts `765....`. What you got there looks line an account id.

**Comment by Zwork101** [comment]
Can you give an example of a steam ID? And how to find it without accessing the other person's account?

**Comment by rossengeorgiev** [comment]
`76561198285283973` using the account id from your code

https://steamcommunity.com/profiles/76561198285283973

**Comment by Zwork101** [comment]
I feel like an idiot right now, could have sworn I've tried that, It sent the request, but the print couldn't execute because it didn't recignize `body`

`Traceback (most recent call last):`

`File "C:\Users\Zwork101\AppData\Local\Programs\Python\Python36-32\Steam_Bot_LogOn.py", line 15,` `in <module>`

    `print("Send a friend request to %s (%d)" % (repr(body.persona_name_added), body.steam_id_added))`

`NameError: name 'body' is not defined`

Maybe because this is python 2 code that I'm moving over to python 3?

**Comment by rossengeorgiev** [comment]
Looks like a bug in the example. It should be `resp.body.persona_name_added` and `body.steam_id_added`

**Comment by Zwork101** [comment]
question, if a sent request is ignored, is it possible to send another without an error?

**Comment by rossengeorgiev** [comment]
If you mean the user that you invited, ignoring the friend request? I don't see why not. However, there are rules, which I don't fully know, that prevent spam inviting. Also, they might block.

**Comment by Zwork101** [comment]
And another question, because I really want to learn this thing inside and out, and I'll admit, I only use python, as a hobby, how do I see who sent me an add friend invite after the `EVENT_FRIEND_INVITE`

`import steam`
`from steam import SteamClient`
`from steam import client`

`SteamFriends = steam.client.builtins.friends.SteamFriendlist`
`client = SteamClient()`
`client.cli_login()`


`if SteamFriends.ready() == False:`
    `print("Error, unable to connect to the Steam friends list")`
`else:`
   ` print("Friends list online")`
`def acceptRequest():`
    `SteamFriends.add(#How do I get steam ID from request?)`
`SteamFriends.on(EVENT_FREIND_INVITE, acceptRequest())` 

Also, I haven't run this code through yet, so there might be other errors

**Comment by rossengeorgiev** [comment]
Oh no, that code doesn't work. You could something like this:

```python
client = SteamClient()

@client.friends.on(client.friends.EVENT_FRIEND_INVITE)
def handle_friend_invite(user):
    print("Received friend invite from: %s (%s)" % (repr(user.name), user.steam_id.community_url))
    client.friends.add(user)  # accept invite

@client.friends.on(client.friends.EVENT_FRIEND_NEW)
def handle_new_friend(user):
    print("New friend: %s (%s)" % (repr(user.name), user.steam_id.community_url))

client.cli_login()
client.run_forever()
```

This will accept every invite

**Comment by Zwork101** [comment]
Is user supplied by the decorators?

**Comment by rossengeorgiev** [comment]
The decorator is a way of registering callbacks. Once the event happens that function is called. This particular event as per documentation will call the function with a single argument. You can name the argument whatever you want. I've renamed it to `friend` in my example to make it more clear.

**Comment by Zwork101** [comment]
It received the invite, however it was not accepted and left me with - 
`TypeError: <SteamUser(76561198285283973, EPersonaState.Offline)> has type <class` `'steam.client.user.SteamUser'>, but expected one of: (<class 'bytes'>, <class 'str'>)`
`Thu Feb  9 13:55:08 2017 <Greenlet at 0x4786ee0:` `handle_friend_invite(<SteamUser(76561198285283973, EPersonaState.Offlin)> failed with TypeError`

**Comment by Zwork101** [comment]
Also, thank you so much, you really good at explaining

**Comment by rossengeorgiev** [comment]
I've changed the example, we need to cast the `SteamUser` instance into `int`.

**Comment by Zwork101** [comment]
At line 9 I added `user = int(user)` and got an error.
What am I doing wrong?

**Comment by rossengeorgiev** [comment]
I've changed the example, my first comment about `int` was incorrect.

**Comment by Zwork101** [comment]
I think I'm confused, but I took your example code above, tried it again, and got the same error. The example you commented 26 minutes ago when this is posted

**Comment by rossengeorgiev** [comment]
Try refreshing the page. I've edited it a couple of times.

**Comment by Zwork101** [comment]
That did the trick, your awesome. And Right now, I have one last question, and all stop bothering you. I want to make it so that when the bot becomes friends with the user, It will send it a message. And that whenever the bot is sent a message, it will check if it's a command it recognizes, and if it does, it will send the user a message, relating to the message sent. Ex. If I sent it the message, !help, it would send back a message containing other commands.

**Comment by Zwork101** [comment]
I think it will look something like this, If I've learned anything this whole time:
`@client.on(client.wait_msg)`
`def handle_new_message(msg):`

**Comment by Zwork101** [comment]
Atleast, its a start

**Comment by rossengeorgiev** [comment]
Here is very basic example of an echo command

```python
@client.on(client.EVENT_CHAT_MESSAGE)
def handle_message(friend, message_text):
    if message_text.startwith('!echo '):
        friend.send_message(message_text.split(' ', 1)[1])

**Comment by Zwork101** [comment]
I'm gonna im implement that, but this is what I did so far
`@client.on(client.wait_msg)`
`def handle_new_message(msg):`
    `helpmessage = MsgProto(EMsg.ClientChatMsg)`
    `helpmessage.body.steamid_to_send = user`
   ` if msg == "!help":`
       ` client.send(helpmessage, EMsg.ClientSendMessageResponse)`

Also, how do I customize that, and what does the split do? Would it take off the '!'?

**Comment by Zwork101** [comment]
After trying this out, it stated that !echo FailedWithoutAttributeError

**Comment by rossengeorgiev** [comment]
I had a typo, its `startswith`, not `startwith`

**Comment by Zwork101** [comment]
It works! So If I did another if statment..
`    if message_text.startswith('!help'):`
       ` friend.send_message("Coming Soon!")`
It should work..

**Comment by Zwork101** [comment]
It works too! Ok, and last question, is it possible to send trades and accept trades?

**Comment by rossengeorgiev** [comment]
No, there is no API for that at the moment.

**Comment by Zwork101** [comment]
Anyway, thanks for being awesome! the bot is http://steamcommunity.com/id/thetf2tradebot/ if you wanna check it out. Thanks for spending some of your time to teach me!

**Comment by rossengeorgiev** [comment]
No problem. Implementing trading might be a difficult task if you are new. I think there are node modules that already implement trading. Good luck
