### ISSUE TITLE
Unable to get get 'connect()' to work

### ISSUE THREAD

**Issue by Zwork101** [ValvePython/steam#72]
I was adding a new function, that would go off on a disconnect, with this code:
`@client.on(client.EVENT_DISCONNECTED)`
`def handleDisconnect():`
   ` print("I've Been disconnected")`
    `print("Attempting to connect")`
    `client.connect()`
However, I had a problem, I could not get connect to work. I don't want to use client.cli_login(), because when logging in, the disconnect triggers, (Thats how it works, I guess), and adding client.cli_login would make it try to connect for forever.

**Comment by rossengeorgiev** [comment]
The login process may require connecting multiple times. It just how steam operates, so you have to be very careful what you put into function attached to the disconnect event.

I suggest you look through https://github.com/ValvePython/steam/tree/master/recipes/1.Login

Another, thing you could is hardcode the credentials and provide them every time on `channel_secured`.

**Comment by Zwork101** [comment]
Is there anyway to accomplish this without a sentry file?

**Comment by rossengeorgiev** [comment]
I'm not sure if relogin works without the sentry file. It's also needed for when you have email based steam guard, otherwise you will need to enter email code every time.

**Comment by Zwork101** [comment]
The sentry file allows for a login with the username and pass, right?

**Comment by rossengeorgiev** [comment]
Sentry file is not necessary for login, but lets you login if you setup Steam Guard to send email code, without entering the email code every time you login.
