### ISSUE TITLE
Question about sending messages to saved profiles

### ISSUE THREAD

**Issue by Zwork101** [ValvePython/steam#74]
Recently @rossengeorgiev has been helping me a lot lately, and in the program, we made the variable 'friend' equal to the person sending the bot messages. However, I recently have tried to save profile information, so the bot can send messages when the other users, without waiting for a response. I tried using `repr` to figure out what the friend is, and got: :` <SteamUser(-a steam id here-, EPersonaState.Online)>` when I tried to replicate this:
```python 3
for i in ChatRoomList:
           roomCode = ChatRoomList[i]
           if roomCode[0] == ChatRoomList[friend.name][0]:
                Temp_send = SteamUser(roomCode[1], EPersonaState.Online)
                Temp_send.send_message(ChatMSG_)
```
Lets say that in this case, `ChatRoomList = {"JoeShmoe":("65465476","65879859"), "JakeCake":("65465476", "54768798")` Joe wanted to send a message to the people in his group, which are in the whole ChatRoomList. He types in his message the program searches through ChatRoomList[i], which will check every user name, and with every username's tuple, it will check the first one, the Chat room code. If it finds a match, `if roomCode[0] == ChatRoomList[friend.name][0]:`, which means that person is the chat room, it will check for the second string in the tuple, which is the user's ID, which it will then save to an object, as a user  `Temp_send = SteamUser(roomCode[1], EPersonaState.Online)`. This is however, where the problem happens, when python states that SteamUser is an unknown object. If thats invalid, what is it? And should the repr be updated?

**Comment by Zwork101** [comment]
_**UPDATE**_
I found how to re-create the friend object, however, I need the EPersonaState variable to do this. However I can only get that by getting the steam user object first? Not sure what to do now.

**Comment by Zwork101** [comment]
So right now, I'm asking how to find the EPersonaState of a selected indivisual, that isn't making contact with the bot at that moment, but has in the past

**Comment by rossengeorgiev** [comment]
`SteamUser` is not intended for direct use. Not sure what you are doing, but if you want to get a `SteamUser` instance you should use `get_user()` method:

http://steam.readthedocs.io/en/latest/api/steam.client.html#steam.client.SteamClient.get_user

The data in persona state is limited depending on the relationship status.

**Comment by Zwork101** [comment]
This is helpful, so I should do `sendmsg =client.get_user(there_ID,False)` then I can sendmsg.send_message("BlahBlah"). Would that work?

**Comment by rossengeorgiev** [comment]
Sure. Or since they are in your friendlist, you can just do `client.friends[steam_id].steam_message('blaaa')`

**Comment by Zwork101** [comment]
You. Are. The. Best. You can close the discussion now
