### ISSUE TITLE
SteamClient proto file

### ISSUE THREAD

**Issue by yzinets** [ValvePython/steam#75]
System: Archlinux
Kernel: 4.9.8-1
Python version: 3.6.0
Steam lib version: 0.8.14

Traceback (most recent call last):
  File "/home/yzinets/Projects/CSGOPolygonAuth/run.py", line 1, in <module>
    from steam.client import SteamClient
  File "/usr/lib/python3.6/site-packages/steam/client/__init__.py", line 27, in <module>
    from steam.core.msg import MsgProto
  File "/usr/lib/python3.6/site-packages/steam/core/msg/__init__.py", line 4, in <module>
    from steam.core.msg.headers import MsgHdr, ExtendedMsgHdr, MsgHdrProtoBuf, GCMsgHdr, GCMsgHdrProto
  File "/usr/lib/python3.6/site-packages/steam/core/msg/headers.py", line 5, in <module>
    from steam.protobufs import gc_pb2
  File "/usr/lib/python3.6/site-packages/steam/protobufs/gc_pb2.py", line 23, in <module>
    serialized_pb=_b('\n\x08gc.proto\"\xe1\x02\n\x12\x43MsgProtoBufHeader\x12\x17\n\x0f\x63lient_steam_id\x18\x01 \x01(\x06\x12\x19\n\x11\x63lient_session_id\x18\x02 \x01(\x05\x12\x15\n\rsource_app_id\x18\x03 \x01(\r\x12+\n\rjob_id_source\x18\n \x01(\x06:\x14\x31\x38\x34\x34\x36\x37\x34\x34\x30\x37\x33\x37\x30\x39\x35\x35\x31\x36\x31\x35\x12+\n\rjob_id_target\x18\x0b \x01(\x06:\x14\x31\x38\x34\x34\x36\x37\x34\x34\x30\x37\x33\x37\x30\x39\x35\x35\x31\x36\x31\x35\x12\x17\n\x0ftarget_job_name\x18\x0c \x01(\t\x12\x12\n\x07\x65result\x18\r \x01(\x05:\x01\x32\x12\x15\n\rerror_message\x18\x0e \x01(\t\x12\x44\n\ngc_msg_src\x18\xc8\x01 \x01(\x0e\x32\x11.GCProtoBufMsgSrc:\x1cGCProtoBufMsgSrc_Unspecified\x12\x1c\n\x13gc_dir_index_source\x18\xc9\x01 \x01(\r*\xb6\x01\n\x10GCProtoBufMsgSrc\x12 \n\x1cGCProtoBufMsgSrc_Unspecified\x10\x00\x12\x1f\n\x1bGCProtoBufMsgSrc_FromSystem\x10\x01\x12 \n\x1cGCProtoBufMsgSrc_FromSteamID\x10\x02\x12\x1b\n\x17GCProtoBufMsgSrc_FromGC\x10\x03\x12 \n\x1cGCProtoBufMsgSrc_ReplySystem\x10\x04')
  File "/usr/lib/python3.6/site-packages/google/protobuf/descriptor.py", line 824, in __new__
    return _message.default_pool.AddSerializedFile(serialized_pb)
TypeError: Couldn't build proto file into descriptor pool!
Invalid proto descriptor for file "gc.proto":
  CMsgProtoBufHeader.target_job_name: "CMsgProtoBufHeader.target_job_name" is already defined in file "steammessages_base.proto".
  CMsgProtoBufHeader.eresult: "CMsgProtoBufHeader.eresult" is already defined in file "steammessages_base.proto".
  CMsgProtoBufHeader.error_message: "CMsgProtoBufHeader.error_message" is already defined in file "steammessages_base.proto".
  CMsgProtoBufHeader: "CMsgProtoBufHeader" is already defined in file "steammessages_base.proto".

**Comment by rossengeorgiev** [comment]
What the.... I can't reproduce this. Can you `pip freeze` ?

**Comment by rossengeorgiev** [comment]
Ok, this looks to be a problem the latest version of the protobuf package `3.2.0`, but only happens on Python >= `3.5`.

**Comment by yzinets** [comment]
Ok. It was a bit problematic but thanks for the reply!

**Comment by rossengeorgiev** [comment]
Just downgrade `protobuf` to `3.0.0` as workaround.

**Comment by rossengeorgiev** [comment]
With protobuf `3.2.0` they've started shipping wheels with the C++ backend, which the requires `package` directive. Pure Python ones ignores that directive as file and directories are used for namespacing.

**Comment by rossengeorgiev** [comment]
I've made a release including the fix. Just upgrade the `steam` package.
