### ISSUE TITLE
Clean up PYPI page for module

### ISSUE THREAD

**Issue by Zwork101** [ValvePython/steam#77]
After browsing pypi.python.org for a python trade api (Anyone know of a good one other than steampy?) and I saw [steam-python0.0](https://pypi.python.org/pypi/steam-python/0.0) and the description was UNKNOWN, I clicked on it, went to the Github page, and what do you know, steam IS steam-python0.0. I think that we need to add a README.md to the page and a description atleast.

                               p.s. Would have labled it as an enhancement, but I dont know how.

**Comment by Zwork101** [comment]
Follow up, there is ANOTHER modual called steam, which is what I assume what It's supposed to be, so why do we also have steam-python?

**Comment by rossengeorgiev** [comment]
That package is just a placeholder.
