### ISSUE TITLE
Can't login using SteamClient

### ISSUE THREAD

**Issue by SaimM95** [ValvePython/steam#78]
I tried the example code provided here - https://github.com/ValvePython/steam/blob/master/recipes/1.Login/one_off_login.py - but after inputting the username and password, i get an email code; I put that in and then nothing happens. Please help.

**Comment by rossengeorgiev** [comment]
I've updated the examples, try now

**Comment by SaimM95** [comment]
Now it freezes after I put the username in :/

**Comment by rossengeorgiev** [comment]
That is strange. Perhaps a problem with your python install or environment
