### ISSUE TITLE
How do I set up a Sentry File?

### ISSUE THREAD

**Issue by Zwork101** [ValvePython/steam#79]
I want to make it so that when steam disconnects the bot, it can reconnect without me having to put in the credentials. I'm not sure where to start. Help?

**Comment by rossengeorgiev** [comment]
Have you tried looking through the documentation?

**Comment by Zwork101** [comment]
I need to set the one of the variable to the location of the sentry file, and use `get_senty(username)` to the bot's account. But I tried that and it didn't work, and I think I'm missing part of what I'm supposed to do.

**Comment by rossengeorgiev** [comment]
http://steam.readthedocs.io/en/latest/api/steam.client.html#steam.client.SteamClient.set_credential_location

http://steam.readthedocs.io/en/latest/api/steam.client.html#steam.client.SteamClient.relogin

**Comment by Zwork101** [comment]
When trying to set the credential location, It left me with this error.` SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape` I was trying to set it to a folder, is this correct?

**Comment by rossengeorgiev** [comment]
What did you set it to?

**Comment by Zwork101** [comment]
A file on my descktop: C:\Users\Zwork101\Desktop\PyBot\SentryFile\

**Comment by rossengeorgiev** [comment]
`\U` is escape sequence for unicode. Either escape all `\` or use raw strings. `r"asdasdasd"`

**Comment by Zwork101** [comment]
It says it's missing the path argument. I tried putting the folder in python's directory, but I had the same error

**Comment by Zwork101** [comment]
New question, how do I get the sentry bytes to store? I'm not sure where they are located

**Comment by rossengeorgiev** [comment]
You set location via `set_credential_location()` and it handled automagically

**Comment by Zwork101** [comment]
Ok, so I've created a .bin file, and it's empty, now how do I store to it?

**Comment by rossengeorgiev** [comment]
You only set the location and the rest is handled by SteamClient. When you
login it will create the file, and use it on subsequent logins.

See the recipe from my previous reply

**Comment by Zwork101** [comment]
Thank you, that makes much more sense now

**Comment by Zwork101** [comment]
Can I login with cli_login to save the information? Because it hasn't saved any information Should I use client.login?

**Comment by rossengeorgiev** [comment]
There is no difference. In the directory you set, there should be at least 'cm_servers.json` after a successful login. If there isn't, you might not have permission to access the directory, or the path you set is wrong.

**Comment by Zwork101** [comment]
I only have the file `zworktradebot-sentry`, and nothing has been written to it.

**Comment by rossengeorgiev** [comment]
That not a file created by SteamClient. You've either not set the credential location, or its pointing to something else. I can't help any further without seeing the code.

**Comment by mactepp** [comment]
Hey mate. I'm having some issues with the `relogin()` method. If I understood what you said, the sentry file will be stored after a successful login and then it can be used on the method to login without credentials. In the recipe, the relogin method is called when the event `"channel_secured"` is emitted. So, the client was supposed to be logged in after that event, right? Sorry if I'm missing something.

**Comment by rossengeorgiev** [comment]
No, sentry file lets you login without having to enter the email code every time. If you have set a credential location it will be managed automatically for you.

`relogin` is essentially `remember password` in your desktop steam client. See docs for details about relogin: http://steam.readthedocs.io/en/stable/api/steam.client.html#steam.client.SteamClient.relogin

**Comment by rossengeorgiev** [comment]
I'm closing this as looks resolved. Feel free to reopen

**Comment by pmdevita** [comment]
I am running the persistentlogin.py example. After I login, it creates the sentry.bin and server json. However, subsequent logins still do the 2FA. Do I have to login through .relogin() or .login() somehow?

Second question, what do I use for the login_key in .login(). Is is the Steam Web API Key?

**Comment by rossengeorgiev** [comment]
Hi @pmdevita 2FA always requires a code. You can use `login_key`, but keep in mind that it might expire if you are not online all the time. After the first login wait for the `new_login_key` event and save the `login_key`. Then you can login with `login(username, login_key="YOUR LOGIN KEY")`.

See http://steam.readthedocs.io/en/stable/api/steam.client.html#steam.client.SteamClient.relogin

**Comment by MateusZ36** [comment]
I'm having a similar problem, set_credential_location is working propperly, cm_servers.json and {user}_sentry.bin are being generated

when I try to relog, it keeps asking me for the 2FA
I tried doing something like this to save the login_key and use it afterwards:

```python
@client.on(EMsg.ClientNewLoginKey)
def new_login_key(msg):
    with open('secrets.json', 'w+') as f:
        f.write(msg.body.login_key)
```
this event is NEVER being called so it never saves

I'm also having trouble with the AUTH_CODE_REQUIRED event, it is not being called on the 1st try, only from the 2nd, code:

```python
@client.on(client.EVENT_AUTH_CODE_REQUIRED)
def auth_code_prompt(is_2fa, code_mismatch):
    if is_2fa:
        print("Missing 2FA Code")
    else:
        print("Missing Email Code")
```
