### ISSUE TITLE
steam + channels, blocking?

### ISSUE THREAD

**Issue by LadaBr** [ValvePython/steam#81]
channels - http://channels.readthedocs.io/en/latest/inshort.html

I'm trying to combine steam, dota2 and channel websockets together but once I start steam client every channel message is blocked. When I try to start new thread for channel message like this:

> t = Thread(target=lambda group_name: 
>                 Group(group_name).send({
>                 'text': json.dumps({
>                     'match_status': 'launch',
>                 }),
>             }), args=([group_name]))
>             t.start()

it works but I end up with this error:

`gevent.hub.LoopExit: ('This operation would block forever', <Hub at 0x7fde7c76b340 epoll pending=0 ref=0 fileno=71>)`

In the end it crashes worker and daphne too.

How can I achiev that steam client functions can send channels messages without any errors?

**Comment by rossengeorgiev** [comment]
SteamClient and its components make use of `gevent`. That might not play with things. You might want to try monkey patching threads:

http://www.gevent.org/gevent.monkey.html#gevent.monkey.patch_thread

Ideally for an webapp, it is best to separate the SteamCLient from the app and use some kind of messaging between the two.
