### ISSUE TITLE
How to get steamId from Steam user 

### ISSUE THREAD

**Issue by d0geda** [ValvePython/steam#83]
How do I get steamID from this -> "<SteamUser(id, somethingOnline)>"

**Comment by rossengeorgiev** [comment]
SteamUser is an internal class. You get instances via `get_user()` method.

What are you trying to do in the first place?

**Comment by d0geda** [comment]
I would like to add a friend and then send him a message.
`@client.friends.on("friend_invite")
def accept_invite(user):
    messageFriendAccept = "Hello, I am Sushirium | Bot. For list of commands use !help" 
    client.friends.add(user)
    time.sleep(2)
    sendMsg = MsgProto(EMsg.ClientFriendMsg)
    sendMsg.body.steamid = user
    sendMsg.body.chat_entry_type = 1
    sendMsg.body.message = messageFriendAccept
    time.sleep(5)
    client.send(sendMsg)`

**Comment by rossengeorgiev** [comment]
You can put multiline code in comments this way:

\`\`\`python
def my_func():
    pass
\`\`\`

Regarding you issue, just use `SteamUser.send_message`

```python
import gevent

@client.friends.on("friend_invite")
def accept_invite(user):
    client.friends.add(user)
    gevent.sleep(2)
    user.send_message("Hello, I am Sushirium | Bot. For list of commands use !help")

**Comment by d0geda** [comment]
Thanks ;)
