### ISSUE TITLE
Sending comment Part 2

### ISSUE THREAD

**Issue by d0geda** [ValvePython/steam#86]
Well I was trying to send comment on some users profile but my code is not working and I don't know what I am missing can somebody please help me?

Code:
```
import steam.webauth as wa

user = wa.WebAuth('Nick', Password')
FACode = raw_input("Code: ")
try:
    session = user.login()
except wa.TwoFactorCodeRequired:
    session = user.login(twofactor_code=FACode)

url = "http://steamcommunity.com/profiles/<USERID>"
data = {'commentthread_Profile_<USERID>_0_textarea': '+rep Nice guy'}
session.post(url,data=data)
```

**Comment by rossengeorgiev** [comment]
I can't help. Use browser's dev console to see what happens when you post comments.

**Comment by philippj** [comment]
The correct url is `http://steamcommunity.com/comment/Profile/post/<USERID>/-1/`

**Comment by d0geda** [comment]
Thanks Philippj I've had to edit my data[] but it works with your link thank you
