### ISSUE TITLE
friends.add() not working

### ISSUE THREAD

**Issue by Koncealed** [ValvePython/steam#88]
Hello, I just started working with your API.

So I'm on the basics now and I want to check my friends list to see if anyone has added me and if so just accept them no matter what. I wrote it and specified the SteamID and it will not add the user.

https://gist.github.com/anonymous/fc354061cc1639ce32415a102f4ad3dd

Hopefully you can help me out with this ,because I can't seem to find the issue

**Comment by d0geda** [comment]
Use 
```from steam.enums import EResult
from steam.core.msg import MsgProto
from steam.enums.emsg import EMsg
from steam import SteamClient
from getpass import getpass

LOGON_DETAILS = {
    'username': raw_input("Steam user: "),
    'password': getpass("Password: "),
}

client = SteamClient()

try:
    code = raw_input("Enter 2FA Code: ")
    client.login(two_factor_code=code, **LOGON_DETAILS)
except:
    raise SystemExit

print("-"*20)
print("Logged on as:", client.user.name)
print("Community profile:", client.steam_id.community_url)
print("Last logon:", client.user.last_logon)
print("Last logoff:", client.user.last_logoff)

message = MsgProto(EMsg.ClientAddFriend)
message.body.steamid_to_add = <USERID>

resp = client.send_message_and_wait(message, EMsg.ClientAddFriendResponse)

if resp.eresult == EResult.OK:
    print "Send a friend request to %s (%d)" % (repr(resp.persona_name_added),
                                               resp.steam_id_added,
                                               )
else:
    print "Error: %s" % EResult(resp.eresult)

client.logout()
```

**Comment by d0geda** [comment]
Try to use handler
```
@client.friends.on("friend_invite")
def accept_invite(user): 
    client.friends.add(user)
    print("Adding user.")
    time.sleep(5)
    user.send_message("Blaa")
```

**Comment by d0geda** [comment]
Actually in you case you are trying to add a friend using id. You have to use the user client.friend.add(x)

**Comment by Koncealed** [comment]
@d0geda 

Okay I see ,but Handles/Events are not working at all. I got it running like this.

https://gist.github.com/anonymous/e208c52ca5caf8892540a8ffe4029e46

**Comment by Koncealed** [comment]
@d0dega even yours is not working, with the event handler.

**Comment by d0geda** [comment]
Try to not have the handler in ``while true
```

@client.friends.on("friend_invite")
def accept_invite(user): 
    client.friends.add(user)
    print("Adding user.")
    time.sleep(5)
    user.send_message("Blaa")
while true:
  #some code

**Comment by rossengeorgiev** [comment]
`SteamClient` doesn't patch time module to be gevent cooperative. You either use `gevent.sleep()` or `gevent.monkey.patch_time()` at the top.

**Comment by rossengeorgiev** [comment]
@Koncealed you are trying to use internal classes. To achieve what you want do something like this:

```python
import gevent
from steam import SteamClient

client = SteamClient()

@client.friends.on("friend_invite")
def accept_invite(user): 
    client.friends.add(user)
    print("Added %s" % repr(user))
    gevent.sleep(5)
    user.send_message("Some message")

client.cli_login()
client.run_forever()

**Comment by Koncealed** [comment]
@rossengeorgiev 

Yes it worked. So final question, when I want to use a class just use client.CLASSNAME.etc, and not import the steam.builtins.friends.FriendList?

**Comment by rossengeorgiev** [comment]
As is stands at the moment, you just use `SteamClient`. Other classes under `steam.client` namespace are used internally.

**Comment by rossengeorgiev** [comment]
I'm closing this as it looks resolved. Feel free to reopen
