### ISSUE TITLE
SteamGuard Authentication

### ISSUE THREAD

**Issue by Koncealed** [ValvePython/steam#92]
Hello I am having an issue with SteamGuard authentication. 

I just want to setup SteamGuard authentication, and seem to be having a hard time.

https://gist.github.com/anonymous/ab7988321297765f647cd6ef830da981

and I keep getting these errors

https://gist.github.com/anonymous/bac7e6d05500556255810cf3f9e80e5b

I cannot seem to find the issue, hopefully someone can help me out thanks!

**Comment by rossengeorgiev** [comment]
You need to initialize SteamAuthenticator with `SteamClient` instance or `WebAuth` instance.

```python
sa = guard.SteamAuthenticator(medium=client)
```

**Comment by Koncealed** [comment]
@rossengeorgiev 
Now once I did that sa.add() does not work.

**Comment by Koncealed** [comment]
@rossengeorgiev I still can't figure out the issue. Hopefully you can shine some light on me.

**Comment by rossengeorgiev** [comment]
You are hitting a bug in gevent and also one in the steam package. Run `pip install -U gevent` and then try.

**Comment by Koncealed** [comment]
@rossengeorgiev 

Still errors https://gist.github.com/anonymous/ec51360c7d797d1e51d9e0305f3888a9
