### ISSUE TITLE
Automatic login possible with 2FA?

### ISSUE THREAD

**Issue by wolfhechel** [ValvePython/steam#94]
I'm trying to build in Python 3.6 with this library but everytime I have to login again.
I had a look at the persistent_login example but it doesn't seem to work either.

Is there anything that needs to be done in order for it to work? I read through the documentation but didn't find any information on this matter.

**Comment by rossengeorgiev** [comment]
You can use `relogin` to reconnect without having to provide credentials. However, the relogin token may expire for unknown to me reasons when you login/logout on your account from other places. 

Alternatively, you can either extract your 2FA secrets from your phone, or unregistered your photo steam authenticator, and use `SteamAuthenticator` from the `steam` package.

**Comment by wolfhechel** [comment]
Thanks for a fast response, but relogin doesn't seem to work.
I notice in the relogin function it checks for username and login_key but neither are set after client init, I tried setting the username myself but is login_key supposed to be extracted from the sentry file? Or what purpose does the sentry file serve?

I'm trying to authenticate with my main account so disabling 2FA isn't really an option for me.

**Comment by rossengeorgiev** [comment]
You get your relogin token after you login successfully. Then you can just call `relogin()`. It described in the docs

**Comment by wolfhechel** [comment]
So there is no way to relogin after my service has shutdown completely and I need to start the application up again?

**Comment by rossengeorgiev** [comment]
Just persist the login token and username to disk. If your service is down for a long time, the login token might expire.

**Comment by wolfhechel** [comment]
Good point, I will try that. Thanks

**Comment by rossengeorgiev** [comment]
Closing this as look resolved, feel free to reopen.
