### ISSUE TITLE
SteamGuard.add() still not working

### ISSUE THREAD

**Issue by Koncealed** [ValvePython/steam#95]
Issue is still not resolved.

Previous Issue - https://github.com/ValvePython/steam/issues/92
But these are the errors https://gist.github.com/anonymous/ec51360c7d797d1e51d9e0305f3888a9

**Comment by rossengeorgiev** [comment]
You could've reopened the old issue. Is your `SteamClient` instanced logged in? If its not, it wont work :)

**Comment by Koncealed** [comment]
@rossengeorgiev SteamClient is 100% connected. Also I couldn't reopen the old issue since you closed it.

**Comment by rossengeorgiev** [comment]
Do you have phone number setup on the account?

**Comment by Koncealed** [comment]
@rossengeorgiev 
100% https://gyazo.com/52f719b95e46d6361971439e83b0f9c3

**Comment by rossengeorgiev** [comment]
I've tested this and the recursion still happens. So, gevent has not fixed the bug.

`python 3.6.1` and `gevent 1.2.1`.

```
[2017-04-17 17:39:47,365] DEBUG SteamClient: get_web_session_cookies error: maximum recursion depth exceeded while calling a Python object

**Comment by rossengeorgiev** [comment]
This bug isn't getting fixed soon, but I have work around. Run `pip install -U steam`. 

I've made an example for adding and then removing the authenticator, see https://gist.github.com/rossengeorgiev/5a9bc286e94b2ee15c7d11324410f3e4

To avoid the bug, do the `gevent.monkey.patch_ssl()` at the very top of you project if you are going to use `SteamClient`.

Alternatively, you can have you project in another version of python that's not `3.6`.
