### ISSUE TITLE
How to remove friends when bot reaches the max

### ISSUE THREAD

**Issue by d0geda** [ValvePython/steam#96]
Well, I would like to remove offline friends when bot reaches maximum of his friends. I would simply need to get friends persona state and if it's offline bot will remove him

I was thinkig of registering a callback
```
@client.friends.on(EFriendRelationship.Max)
def max_friends():
    for friend in client.friends:
        if """Persona state""" == "Offline"
            client.friends.remove(friend)
```
But I don't know how to return a persona state

**Comment by rossengeorgiev** [comment]
I'm not sure how to check what the max friend list size is. It changes based on account level.

You can loop over the friend list:

```python

for friend in client.friends:
    if friend.state == EPersonaState.Offline:
        client.friends.remove(friend)

**Comment by d0geda** [comment]
Thanks
