### ISSUE TITLE
How can I send a protobuf message that is not defined in emsg?

### ISSUE THREAD

**Issue by mactepp** [ValvePython/steam#99]
Sorry for bothering you with this simple question, but I can't manage to make this work. I tried doing things like this but nothing seems to work.
```
def get_inventory(appid, otherid):
    message = Msg(CInventory_GetInventory_Request)
    message.body = CInventory_GetInventory_Request()
    message.body.appid = appid
    message.body.steamid = otherid
    client.send(message)
```

**Comment by rossengeorgiev** [comment]
All these are `unified messages`. The docs describe how you can use those. See http://steam.readthedocs.io/en/latest/api/steam.client.builtins.html#module-steam.client.builtins.unified_messages

**Comment by mactepp** [comment]
Got it. I wasn't sure about that. I thought the unified messages had other purposes. Thanks for your time
